# -*- coding: utf-8 -*-
"""Catalogo unico de imagenes: que fichero exacto de Wikimedia Commons usa cada foto.

Es la fuente de verdad del repo. `descargar.py` resuelve cada entrada contra la API de
Commons, guarda el JPEG en img/<grupo>/<slug>.jpg y escribe los creditos en
img/creditos.json. Al fijar el fichero por su titulo —y no por una busqueda— el build
sale igual hoy que dentro de un ano: nada depende de como ordene Commons los resultados.

Regla: cada foto tiene que ser DE LO QUE DICE EL PIE. Se comprobo una por una.
"""

# (slug, pie de foto, fichero en Commons — sin el prefijo "File:")
LUGARES = [
    # --- portada y Windhoek ---
    ("portada", "Deadvlei al amanecer — el motivo del viaje",
     "Petrified In Time (200653949).jpeg"),
    ("windhoek", "La Christuskirche de Windhoek, el punto de entrada y de salida",
     "Iglesia de Cristo, Windhoek, Namibia, 2018-08-04, DD 02.jpg"),
    ("joes", "Joe's Beerhouse: la opción de mesa del D0 y el D13",
     "Joes-Beerhouse Windhoek-Namibia1.jpg"),

    # --- desierto: D2 a D4 ---
    ("spreetshoogte", "El paso de Spreetshoogte, con el Namib mil metros abajo",
     "Spreetshoogte Pass panorama.jpg"),
    ("solitaire", "Solitaire: gasolina, tarta de manzana y coches oxidados",
     "Solitaire, Namibia (17143158888).jpg"),
    ("namib-paisaje", "El Namib-Naukluft camino de Sesriem",
     "Paisaje en el parque nacional de Namib-Naukluft, Namibia, 2018-08-06, DD 08.jpg"),
    ("sesriem", "El cañón de Sesriem, a diez minutos de la puerta",
     "Cañón Sesriem, Sossusvlei, Namibia, 2018-08-06, DD 177-185 PAN.jpg"),
    ("sossusvlei", "Sossusvlei: el final del río Tsauchab, tragado por las dunas",
     "Sossusvlei, Namibia, 2018-08-06, DD 050-054 PAN.jpg"),
    ("deadvlei", "Los árboles muertos de Deadvlei: 900 años secos y de pie",
     "Dead Vlei, Sossusvlei, Namibia, 2018-08-06, DD 086.jpg"),
    ("bigdaddy", "Big Daddy desde el vlei, con un órix de escala",
     "Oryx in front of Big Daddy Dune, Sossusvlei, Namibia.jpg"),
    ("hiddenvlei", "Hidden Vlei, el vlei escondido: 1,3 km de arena y casi nadie",
     "Hidden Vlei, Namibia.jpg"),
    ("duna45", "Duna 45 al amanecer, en el kilómetro 45 de la carretera de Sossusvlei",
     "006 Dune 45 in Sossusvlei at sunrise Photo by Giles Laurent.jpg"),
    ("cielo", "El cielo del desierto namibio, sin una luz en cien kilómetros",
     "Kanaan-Lodge 1901-0042.jpg"),

    # --- costa: D5 a D7 ---
    ("walvisbay", "Flamencos en la laguna de Walvis Bay",
     "NA-walvisbay-lagoon-famingo.jpg"),
    ("swakopmund", "El embarcadero de Swakopmund, la costa alemana",
     "Jetty, Swakopmund, Namibia, 2018-08-04, DD 57-60 PAN.jpg"),
    ("sandwich", "Sandwich Harbour desde el aire: donde la duna cae al Atlántico",
     "Sandwich Harbour (Luftaufnahme).jpg"),
    ("saltroad", "La C34, la carretera de sal: firme de costra salina y niebla",
     "Salt Road Junction - C34 & D2303 (3691742500).jpg"),
    ("capecross", "La colonia de lobos marinos de Cape Cross",
     "133 Group of Cape fur seal sleeping together at Cape cross Photo by Giles Laurent.jpg"),
    ("skeleton", "La Costa de los Esqueletos y sus naufragios",
     "Shipwreck in Skeleton Coast (16683455783).jpg"),
    ("terracebay", "Terrace Bay: la última señal de vida al norte de la costa",
     "Terrace Bay, Skeleton Coast - panoramio.jpg"),
    ("welwitschia", "Welwitschia mirabilis: dos hojas y mil años de vida",
     "Welwitschia mirabilis - Namib-Naukluft National Park 03.jpg"),

    # --- Damaraland: D8 ---
    ("twyfelfontein", "Los grabados rupestres de Twyfelfontein, patrimonio UNESCO",
     "Rock Engravings (37713171646).jpg"),
    ("damaraland", "Damaraland, camino de Grootberg",
     "Damaraland 10.jpg"),
    ("grootberg", "El paso de Grootberg, subiendo hacia Hoada",
     "Grootberg Pass (37090707863).jpg"),
    ("hoada", "El campamento de Hoada, entre peñas de granito",
     "Rocks and Trees at Hoada Campsite Grootberg (37051940074).jpg"),
    ("circulos", "Los círculos de hadas, vistos desde el aire",
     "Aerial view of Fairy circles, Namibia (2017).jpg"),

    # --- Etosha: D9 a D12 ---
    ("etosha-pan-satelite", "La depresión de Etosha desde la Estación Espacial",
     "The Etosha Pan (gmt306 16 27 for-esa andreas-mogensen etosha-pan).jpg"),
    ("etosha-pan", "La costra de sal de la depresión, a ras de suelo",
     "White salt surface of the Etosha Pan under a blue sky, Namibia, 2007.jpg"),
    ("okaukuejo", "La charca de Okaukuejo, la del chalet y la luz de noche",
     "Drinking Giraffe at the Okaukuejo Waterhole, Etosha National Park, Namibia.jpg"),
    ("etosha-elefantes", "Familia de elefantes en la charca de Gemsbokvlakte",
     "Elephant family at Gemsbokvlakte waterhole, Etosha National Park, Namibia.jpg"),
    ("etosha-rino", "Rinoceronte negro en Etosha: el premio de la charca iluminada",
     "Diceros bicornis (Etosha).jpg"),
    ("etosha-jirafas", "Jirafas angoleñas al atardecer en Etosha",
     "077 Angolan giraffes cuddling at sunset in Etosha National Park Photo by Giles Laurent.jpg"),
    ("halali", "El campamento de Halali, al pie de su koppie",
     "Etosha-Halali Camp (1).jpg"),
    ("namutoni", "El fuerte de Namutoni, cuartel colonial reconvertido en campamento",
     "Namutomi Fort (37073116643).jpg"),

    # --- transversales ---
    ("grava", "La pista de grava: donde vive el riesgo del viaje",
     "Namibia D826.JPG"),
    ("hilux", "Un Hilux con tiendas de techo en Namibia, como el vuestro",
     "Toyota Hilux D-4D with roof tents.jpg"),
    ("termitero", "Termitero en la sabana",
     "Dunst Namibia Oct 2002 slide342 - Termitenbau.jpg"),
]

# ---------------------------------------------------------------------------
# Fauna: (slug, nombre_es, nombre_en, cientifico, fichero en Commons)
# ---------------------------------------------------------------------------

MAMIFEROS = [
    ('elefante', 'Elefante africano de sabana', 'African bush elephant', 'Loxodonta africana',
     '178 Male African bush elephant in Etosha National Park Photo by Giles Laurent.jpg'),
    ('rino-negro', 'Rinoceronte negro', 'Black rhinoceros', 'Diceros bicornis',
     'Black Rhino at Working with Wildlife.jpg'),
    ('rino-blanco', 'Rinoceronte blanco', 'White rhinoceros', 'Ceratotherium simum',
     '109 Male White rhinoceros walking in the Kalahari Desert of Namibia Photo by Giles Laurent.jpg'),
    ('leon', 'León', 'Lion', 'Panthera leo',
     '020 The lion king Snyggve in the Serengeti National Park Photo by Giles Laurent.jpg'),
    ('leopardo', 'Leopardo', 'Leopard', 'Panthera pardus',
     'African leopard male (cropped).jpg'),
    ('guepardo', 'Guepardo', 'Cheetah', 'Acinonyx jubatus',
     'Male cheetah facing left in South Africa.jpg'),
    ('jirafa', 'Jirafa angoleña', 'Angolan giraffe', 'Giraffa giraffa angolensis',
     '106 Angolan giraffe walking in the Kalahari Desert of Namibia Photo by Giles Laurent.jpg'),
    ('cebra-burchell', 'Cebra de Burchell', "Burchell's zebra", 'Equus quagga burchellii',
     'Equus quagga burchellii - Etosha, 2014.jpg'),
    ('cebra-hartmann', 'Cebra de montaña de Hartmann', "Hartmann's mountain zebra", 'Equus zebra hartmannae',
     'Equus zebra hartmannae - Etosha 2015.jpg'),
    ('orix', 'Órix o gemsbok', 'Gemsbok', 'Oryx gazella',
     'Gemsbok (Oryx gazella) male.jpg'),
    ('springbok', 'Springbok', 'Springbok', 'Antidorcas marsupialis',
     '174 Male Springbok in Etosha National Park Photo by Giles Laurent.jpg'),
    ('kudu', 'Gran kudú', 'Greater kudu', 'Tragelaphus strepsiceros',
     'Male greater kudu.jpg'),
    ('eland', 'Eland común', 'Common eland', 'Taurotragus oryx',
     'Taurotragus oryx - young bull - Etosha 2015.jpg'),
    ('nu', 'Ñu azul', 'Blue wildebeest', 'Connochaetes taurinus',
     'Wildebeest of Etosha National Park.jpg'),
    ('impala-cara-negra', 'Impala de cara negra', 'Black-faced impala', 'Aepyceros melampus petersi',
     'Impala (Aepyceros melampus) male Kruger.jpg'),
    ('dikdik', 'Dik-dik de Damara', 'Damara dik-dik', 'Madoqua damarensis',
     'Madoqua kirkii - male (Namutoni).jpg'),
    ('hiena-manchada', 'Hiena manchada', 'Spotted hyena', 'Crocuta crocuta',
     'Spotted hyena (Crocuta crocuta).jpg'),
    ('hiena-parda', 'Hiena parda', 'Brown hyena', 'Parahyaena brunnea',
     'Brown Hyena (Hyaena brunnea) leaving waterhole ... (50915531592), crop.jpg'),
    ('chacal', 'Chacal de lomo negro', 'Black-backed jackal', 'Lupulella mesomelas',
     '135 Black-backed jackal hunting for food at Cape cross Photo by Giles Laurent.jpg'),
    ('ratel', 'Ratel o tejón de la miel', 'Honey badger', 'Mellivora capensis',
     'Honey Badger.jpg'),
    ('facocero', 'Facóquero', 'Common warthog', 'Phacochoerus africanus',
     'Southern warthog (Phacochoerus africanus sundevallii) male.jpg'),
    ('suricata', 'Suricata', 'Meerkat', 'Suricata suricatta',
     'Meerkat (Suricata suricatta) Tswalu.jpg'),
    ('hartebeest', 'Alcélafo rojo', 'Red hartebeest', 'Alcelaphus buselaphus caama',
     '2011-Red-Hartebeest.jpg'),
    ('steenbok', 'Steenbok', 'Steenbok', 'Raphicerus campestris',
     'Raphicerus campestris male (Etosha, 2012).jpg'),
    ('zorro-orejudo', 'Zorro orejudo', 'Bat-eared fox', 'Otocyon megalotis',
     'Otocyon megalotis - Etosha 2014.jpg'),
    ('jineta', 'Jineta de manchas pequeñas', 'Small-spotted genet', 'Genetta genetta',
     'A female common genet in the dining room, Satao Camp, Tsavo East.jpg'),
    ('puercoespin', 'Puercoespín del Cabo', 'Cape porcupine', 'Hystrix africaeaustralis',
     'Hystrix africaeaustralis Blijdorp Rotterdam.JPG'),
    ('liebre-saltadora', 'Liebre saltadora', 'Springhare', 'Pedetes capensis',
     'Spring Hare (Pedetes capensis) (6042009463).jpg'),
    ('klipspringer', 'Klipspringer o saltarrocas', 'Klipspringer', 'Oreotragus oreotragus',
     'Klipspringer.jpg'),
    ('mangosta-amarilla', 'Mangosta amarilla', 'Yellow mongoose', 'Cynictis penicillata',
     '082 Yellow mongoose in Khomas Region Photo by Giles Laurent.jpg'),
    ('oricteropo', 'Oricteropo o cerdo hormiguero', 'Aardvark', 'Orycteropus afer',
     'Orycteropus afer 175359469.jpg'),
    ('babuino-chacma', 'Babuino chacma', 'Chacma baboon', 'Papio ursinus',
     'Chacma baboon (Papio ursinus griseipes) male head.jpg'),
]

AVES = [
    ('avestruz', 'Avestruz común', 'Common ostrich', 'Struthio camelus',
     'Struthio camelus - Etosha 2014 (3).jpg'),
    ('avutarda-kori', 'Avutarda kori', 'Kori bustard', 'Ardeotis kori',
     'Kori bustard (Ardeotis kori kori) male.jpg'),
    ('secretario', 'Secretario', 'Secretarybird', 'Sagittarius serpentarius',
     'Secretary bird Mara for WC.jpg'),
    ('carraca-lila', 'Carraca lila', 'Lilac-breasted roller', 'Coracias caudatus',
     '143 Lilac-breasted roller in Etosha National Park Photo by Giles Laurent.jpg'),
    ('calao-amarillo', 'Cálao de pico amarillo sureño', 'Southern yellow-billed hornbill', 'Tockus leucomelas',
     '155 Southern yellow-billed hornbill in Etosha National Park Photo by Giles Laurent.jpg'),
    ('calao-rojo', 'Cálao de pico rojo sureño', 'Southern red-billed hornbill', 'Tockus rufirostris',
     'Southern red-billed hornbill (Tockus rufirostris) male, crop.jpg'),
    ('tejedor-republicano', 'Tejedor republicano', 'Sociable weaver', 'Philetairus socius',
     'Sociable weaver (Philetairus socius).jpg'),
    ('aguila-marcial', 'Águila marcial', 'Martial eagle', 'Polemaetus bellicosus',
     'Martial eagle (Polemaetus bellicosus).jpg'),
    ('buitre-dorsiblanco', 'Buitre dorsiblanco africano', 'White-backed vulture', 'Gyps africanus',
     '2012-white-backed-vulture.jpg'),
    ('flamenco-enano', 'Flamenco enano', 'Lesser flamingo', 'Phoeniconaias minor',
     'Flock of Lesser Flamingo along with juvenile near Jamnagar railway stationDSCN1798 1.jpg'),
    ('grulla-azul', 'Grulla azul', 'Blue crane', 'Grus paradisea',
     'Grus paradisea Etosha 1.jpg'),
    ('ganga-namaqua', 'Ganga namaqua', 'Namaqua sandgrouse', 'Pterocles namaqua',
     '2012-namaqua-sandgrouse-male.jpg'),
    ('sison-negro', 'Sisón negro norteño', 'Northern black korhaan', 'Afrotis afraoides',
     'Northern black korhaan (Afrotis afraoides) male.jpg'),
    ('azor-lagartijero', 'Azor lagartijero claro', 'Pale chanting goshawk', 'Melierax canorus',
     'Melierax canorus-01.jpg'),
    ('alcaudon-carmesi', 'Alcaudón de pecho carmesí', 'Crimson-breasted shrike', 'Laniarius atrococcineus',
     '161 Crimson-breasted shrike in Otjozondjupa Region Photo by Giles Laurent.jpg'),
    ('buho-lacteo', 'Búho lácteo de Verreaux', "Verreaux's eagle-owl", 'Bubo lacteus',
     '2012-giant-eagle-owl.jpg'),
    ('abejaruco-europeo', 'Abejaruco europeo', 'European bee-eater', 'Merops apiaster',
     'Bee-eater (19270331108).jpg'),
    ('ciguena-abdim', 'Cigüeña de Abdim', "Abdim's stork", 'Ciconia abdimii',
     'Ciconia abdimii -London Zoo-8a.jpg'),
    ('estornino-cabo', 'Estornino brillante del Cabo', 'Cape starling', 'Lamprotornis nitens',
     '159 Cape starling in Etosha National Park Photo by Giles Laurent.jpg'),
    ('pigargo-vocinglero', 'Pigargo vocinglero', 'African fish eagle', 'Icthyophaga vocifer',
     'African fish eagle, Haliaeetus vocifer, at Chobe National Park, Botswana (33516612831).jpg'),
    ('pelicano', 'Pelícano blanco común', 'Great white pelican', 'Pelecanus onocrotalus',
     'Great white pelican (Pelecanus onocrotalus).jpg'),
    ('bateleur', 'Águila volatinera o bateleur', 'Bateleur', 'Terathopius ecaudatus',
     'Bataleur - Kruger National park (37161617713).jpg'),
    ('buitre-orejudo', 'Buitre orejudo', 'Lappet-faced vulture', 'Torgos tracheliotos',
     '2012-lappet-faced-vulture.jpg'),
    ('flamenco-comun', 'Flamenco común', 'Greater flamingo', 'Phoenicopterus roseus',
     '010 Greater flamingos male and female in the Camargue during mating season Photo by Giles Laurent.jpg'),
    ('cormoran-cabo', 'Cormorán del Cabo', 'Cape cormorant', 'Phalacrocorax capensis',
     'Phalacrocorax capensis - Namib 2013.jpg'),
    ('charran-damara', 'Charrán damara', 'Damara tern', 'Sternula balaenarum',
     'Damara Tern (8077271589).jpg'),
    ('ostrero-africano', 'Ostrero africano', 'African oystercatcher', 'Haematopus moquini',
     'African Black Oystercatcher (2).JPG'),
    ('francolin-picorrojo', 'Francolín de pico rojo', 'Red-billed spurfowl', 'Pternistis adspersus',
     '2011-red-billed-francolin.jpg'),
]

REPTILES = [
    ('vibora-bufadora', 'Víbora bufadora', 'Puff adder', 'Bitis arietans',
     'Bitis arietans by Danny S. 1.JPG'),
    ('cobra-cebra', 'Cobra escupidora cebra', 'Zebra spitting cobra', 'Naja nigricincta',
     'Naja nigricincta nigricincta.jpg'),
    ('mamba-negra', 'Mamba negra', 'Black mamba', 'Dendroaspis polylepis',
     'Dendroaspis polylepis (14).jpg'),
    ('vibora-peringuey', 'Víbora de Péringuey', "Peringuey's adder", 'Bitis peringueyi',
     'Namibian Sidewinder Bitis peringueyi.jpg'),
    ('vibora-cornuda', 'Víbora cornuda', 'Horned adder', 'Bitis caudalis',
     'Bitis caudalis00a.jpg'),
    ('camaleon-namib', 'Camaleón del Namib', 'Namaqua chameleon', 'Chamaeleo namaquensis',
     'Chamaeleo namaquensis (Walvis Bay).jpg'),
    ('gecko-palmato', 'Gecko palmeado del Namib', 'Web-footed gecko', 'Pachydactylus rangei',
     'Pachydactylus-rangei.jpg'),
    ('agama-namibia', 'Agama de roca de Namibia', 'Namibian rock agama', 'Agama planiceps',
     'Namib rock agama (Agama planiceps) male.jpg'),
    ('varano-roca', 'Varano de roca', 'Rock monitor', 'Varanus albigularis',
     'White-throated Monitor (Varanus albigularis) (32184691034).jpg'),
    ('tortuga-leopardo', 'Tortuga leopardo', 'Leopard tortoise', 'Stigmochelys pardalis',
     'Leopard Tortoise (Stigmochelys pardalis) (17331907085).jpg'),
    ('lagarto-pala', 'Lagarto de nariz de pala', 'Shovel-snouted lizard', 'Meroles anchietae',
     'Meroles anchietae 345390261.jpg'),
]

COSTA = [
    ('lobo-marino', 'Lobo marino del Cabo', 'Cape fur seal', 'Arctocephalus pusillus',
     'Arctocephalus pusillus - SE Tasmania.jpg'),
    ('delfin-heaviside', 'Delfín de Heaviside', "Heaviside's dolphin", 'Cephalorhynchus heavisidii',
     'Dolphins at Lüderitz, Namibia (3144863196).jpg'),
    ('ballena-jorobada', 'Ballena jorobada', 'Humpback whale', 'Megaptera novaeangliae',
     '001 Humpback whale breaching in Ballena Marine National Park Photo by Giles Laurent.jpg'),
    ('daman', 'Damán roquero', 'Rock hyrax', 'Procavia capensis',
     'Rock hyrax Serengeti National Park.jpg'),
    ('ardilla-terrestre', 'Ardilla terrestre del Cabo', 'Cape ground squirrel', 'Xerus inauris',
     'Cape ground squirrel, Xerus inauris, at Krugersdorp Game Reserve, Gauteng, South Africa (27410204561).jpg'),
]

BICHOS = [
    ('escarabajo-niebla', 'Escarabajo de la niebla', 'Fog-basking beetle', 'Onymacris unguicularis',
     'Onymacris unguicularis (Sudan).jpg'),
    ('escorpion', 'Escorpión de cola gruesa', 'Black hairy thick-tailed scorpion', 'Parabuthus villosus',
     'Parabuthus villosus.jpg'),
    ('arana-rueda', 'Araña blanca del Namib', 'Dancing white lady spider', 'Leucorchestris arenicola',
     'Leucorchestris arenicola.jpg'),
    ('termita', 'Termita constructora', 'Termite', 'Macrotermes michaelseni',
     'Macrotermes michaelseni.jpg'),
    ('escarabajo-pelotero', 'Escarabajo pelotero', 'Dung beetle', 'Scarabaeus satyrus',
     'Scarabaeus satyrus (Boheman, 1860) (3847992837) (2).jpg'),
    ('solifugo', 'Solífugo o araña camello', 'Sun spider / camel spider', 'Solifugae',
     'Solifuge in Trinidad, Colorado, July 2026.jpg'),
    ('gusano-mopane', 'Gusano de mopane', 'Mopane worm', 'Gonimbrasia belina',
     'Colophospermum mopane 50D 0486.jpg'),
    ('shongololo', 'Milpiés gigante o shongololo', 'Giant African millipede', 'Archispirostreptus gigas',
     'Archispirostreptus-Gigas-Amphitheatre.jpg'),
    ('anofeles', 'Mosquito anofeles', 'Anopheles mosquito', 'Anopheles',
     'Anopheles stephensi.jpeg'),
]

GRUPOS_FAUNA = [
    ('mamifero', 'Mamíferos', MAMIFEROS),
    ('ave', 'Aves', AVES),
    ('reptil', 'Reptiles', REPTILES),
    ('costa', 'La costa, la roca y la arena', COSTA),
    ('bicho', 'Bichos', BICHOS),
]
