# -*- coding: utf-8 -*-
"""Catalogo unico de imagenes: que fichero exacto de Wikimedia Commons usa cada foto.

Es la fuente de verdad del repo. `descargar.py` resuelve cada entrada contra la API de
Commons, guarda el JPEG en img/<grupo>/<slug>.jpg y escribe los creditos en
img/creditos.json. Al fijar el fichero por su titulo —y no por una busqueda— el build
sale igual hoy que dentro de un ano: nada depende de como ordene Commons los resultados.

Regla: cada foto tiene que ser DE LO QUE DICE EL PIE. Se comprobo una por una.
"""

# (slug, pie de foto, fichero en Commons — sin el prefijo "File:")
LUGARES = [
    # --- portada y Windhoek ---
    ("portada", "Deadvlei al amanecer — el motivo del viaje",
     "Petrified In Time (200653949).jpeg"),
    ("windhoek", "La Christuskirche de Windhoek, el punto de entrada y de salida",
     "Iglesia de Cristo, Windhoek, Namibia, 2018-08-04, DD 02.jpg"),
    ("joes", "Joe's Beerhouse: la opción de mesa del D1 y el D14",
     "Joes-Beerhouse Windhoek-Namibia1.jpg"),

    # --- desierto: D2 a D4 ---
    ("spreetshoogte", "El paso de Spreetshoogte, con el Namib mil metros abajo",
     "Spreetshoogte Pass panorama.jpg"),
    ("solitaire", "Solitaire: gasolina, tarta de manzana y coches oxidados",
     "Solitaire, Namibia (17143158888).jpg"),
    ("namib-paisaje", "El Namib-Naukluft camino de Sesriem",
     "Paisaje en el parque nacional de Namib-Naukluft, Namibia, 2018-08-06, DD 08.jpg"),
    ("sesriem", "El cañón de Sesriem, a diez minutos de la puerta",
     "Cañón Sesriem, Sossusvlei, Namibia, 2018-08-06, DD 177-185 PAN.jpg"),
    ("sossusvlei", "Sossusvlei: el final del río Tsauchab, tragado por las dunas",
     "Sossusvlei, Namibia, 2018-08-06, DD 050-054 PAN.jpg"),
    ("deadvlei", "Los árboles muertos de Deadvlei: 900 años secos y de pie",
     "Dead Vlei, Sossusvlei, Namibia, 2018-08-06, DD 086.jpg"),
    ("bigdaddy", "Big Daddy desde el vlei, con un órix de escala",
     "Oryx in front of Big Daddy Dune, Sossusvlei, Namibia.jpg"),
    ("hiddenvlei", "Hidden Vlei, el vlei escondido: 1,3 km de arena y casi nadie",
     "Hidden Vlei, Namibia.jpg"),
    ("duna45", "Duna 45 al amanecer, en el kilómetro 45 de la carretera de Sossusvlei",
     "006 Dune 45 in Sossusvlei at sunrise Photo by Giles Laurent.jpg"),
    ("cielo", "El cielo del desierto namibio, sin una luz en cien kilómetros",
     "Kanaan-Lodge 1901-0042.jpg"),

    # --- costa: D5 a D7 ---
    ("walvisbay", "Flamencos en la laguna de Walvis Bay",
     "NA-walvisbay-lagoon-famingo.jpg"),
    ("swakopmund", "El embarcadero de Swakopmund, la costa alemana",
     "Jetty, Swakopmund, Namibia, 2018-08-04, DD 57-60 PAN.jpg"),
    ("sandwich", "Sandwich Harbour desde el aire: donde la duna cae al Atlántico",
     "Sandwich Harbour (Luftaufnahme).jpg"),
    ("saltroad", "La C34, la carretera de sal: firme de costra salina y niebla",
     "Salt Road Junction - C34 & D2303 (3691742500).jpg"),
    ("capecross", "La colonia de lobos marinos de Cape Cross",
     "133 Group of Cape fur seal sleeping together at Cape cross Photo by Giles Laurent.jpg"),
    ("skeleton", "La Costa de los Esqueletos y sus naufragios",
     "Shipwreck in Skeleton Coast (16683455783).jpg"),
    ("terracebay", "Terrace Bay: la última señal de vida al norte de la costa",
     "Terrace Bay, Skeleton Coast - panoramio.jpg"),
    ("welwitschia", "Welwitschia mirabilis: dos hojas y mil años de vida",
     "Welwitschia mirabilis - Namib-Naukluft National Park 03.jpg"),

    # --- Damaraland: D8 y D9 ---
    ("twyfelfontein", "Los grabados rupestres de Twyfelfontein, patrimonio UNESCO",
     "Rock Engravings (37713171646).jpg"),
    ("damaraland", "Damaraland, camino de Grootberg",
     "Damaraland 10.jpg"),
    ("grootberg", "El paso de Grootberg, subiendo hacia Hoada",
     "Grootberg Pass (37090707863).jpg"),
    ("hoada", "El campamento de Hoada, entre peñas de granito",
     "Rocks and Trees at Hoada Campsite Grootberg (37051940074).jpg"),
    ("circulos", "Los círculos de hadas, vistos desde el aire",
     "Aerial view of Fairy circles, Namibia (2017).jpg"),

    # --- Etosha: D10 a D13 ---
    ("etosha-pan-satelite", "La depresión de Etosha desde la Estación Espacial",
     "The Etosha Pan (gmt306 16 27 for-esa andreas-mogensen etosha-pan).jpg"),
    ("etosha-pan", "La costra de sal de la depresión, a ras de suelo",
     "White salt surface of the Etosha Pan under a blue sky, Namibia, 2007.jpg"),
    ("okaukuejo", "La charca de Okaukuejo, la del chalet y la luz de noche",
     "Drinking Giraffe at the Okaukuejo Waterhole, Etosha National Park, Namibia.jpg"),
    ("etosha-elefantes", "Familia de elefantes en la charca de Gemsbokvlakte",
     "Elephant family at Gemsbokvlakte waterhole, Etosha National Park, Namibia.jpg"),
    ("etosha-rino", "Rinoceronte negro en Etosha: el premio de la charca iluminada",
     "Diceros bicornis (Etosha).jpg"),
    ("etosha-jirafas", "Jirafas angoleñas al atardecer en Etosha",
     "077 Angolan giraffes cuddling at sunset in Etosha National Park Photo by Giles Laurent.jpg"),
    ("halali", "El campamento de Halali, al pie de su koppie",
     "Etosha-Halali Camp (1).jpg"),
    ("namutoni", "El fuerte de Namutoni, cuartel colonial reconvertido en campamento",
     "Namutomi Fort (37073116643).jpg"),

    # --- los tres campamentos por dentro (doc 21, investigación del 14/08) ---
    ("okaukuejo-torre", "La torre de Okaukuejo, el mirador de 1963 sobre las llanuras",
     "Tower at Okaukuejo (3688062966).jpg"),
    ("okaukuejo-charca-dia", "El murete de observación de la charca de Okaukuejo, de día",
     "Okaukuejo waterhole 2014.JPG"),
    ("okaukuejo-charca-noche", "La charca de Okaukuejo de noche: rinoceronte bajo el foco",
     "White rhinos at Okaukuejo waterhole at night (3687260675).jpg"),
    ("halali-moringa", "Elefantes al atardecer en la charca Moringa de Halali",
     "Wasserloch Halali.jpg"),
    ("halali-piscina", "La piscina de Halali, la siesta del mediodía del D11",
     "Etosha-Halali Camp (2).jpg"),
    ("namutoni-charca", "Leona de noche junto a la charca King Nehale, tras la valla de Namutoni",
     "Lionness Namutoni water hole.jpg"),
    ("namutoni-atardecer", "El atardecer desde la torre del fuerte de Namutoni",
     "Sunset viewed from Fort Namutoni in Etosha National Park, Namibia, 2007.jpg"),

    # --- transversales ---
    ("grava", "La pista de grava: donde vive el riesgo del viaje",
     "Namibia D826.JPG"),
    ("hilux", "Un Hilux con tiendas de techo en Namibia, como el vuestro",
     "Toyota Hilux D-4D with roof tents.jpg"),
    ("termitero", "Termitero en la sabana",
     "Dunst Namibia Oct 2002 slide342 - Termitenbau.jpg"),

    # --- reservas privadas (investigación del 12/08, aparte/reservas-privadas-vs-etosha.md) ---
    ("ongava", "Turdoide caricalvo en Andersson's at Ongava, junto a la puerta Andersson",
     "Bare-cheeked Babbler-5996 - Flickr - Ragnhild & Neil Crawford.jpg"),
    ("onguma", "Manada de leones en Onguma Game Reserve, junto a la puerta Von Lindequist",
     "Löwe (Panthera leo), Rudel ruhend.jpg"),
    ("okonjima", "Mirador al atardecer sobre Okonjima Nature Reserve",
     "Okonjima Nature Reserve.jpg"),
    ("palmwag", "El comedor de Palmwag Lodge, en Damaraland",
     "Interior of lodge (3690395368).jpg"),
    ("hobatere", "Cebra de montaña de Hartmann en Hobatere, al oeste de Etosha",
     "Hartmann zebra hobatere S.jpg"),
]

# ---------------------------------------------------------------------------
# Fauna: (slug, nombre_es, nombre_en, cientifico, fichero en Commons)
# ---------------------------------------------------------------------------

# Los felinos van aparte desde el 15/08: es lo que mas interesa a quien viaja, y asi se
# encuentran de un vistazo. Namibia tiene siete; el serval no toca esta ruta (cero
# registros en las cuatro zonas) y por eso no esta.
FELINOS = [
    ('leon', 'León', 'Lion', 'Panthera leo',
     '020 The lion king Snyggve in the Serengeti National Park Photo by Giles Laurent.jpg'),
    ('leopardo', 'Leopardo', 'Leopard', 'Panthera pardus',
     'African leopard male (cropped).jpg'),
    ('guepardo', 'Guepardo', 'Cheetah', 'Acinonyx jubatus',
     'Male cheetah facing left in South Africa.jpg'),
    ('caracal', 'Caracal', 'Caracal', 'Caracal caracal',
     'Caracl (01), Paris, décembre 2013.jpg'),
    ('gato-montes-africano', 'Gato montés africano', 'African wildcat', 'Felis lybica',
     'African Wildcat (Felis lybica) (51659798835).jpg'),
    ('gato-patas-negras', 'Gato de patas negras', 'Black-footed cat', 'Felis nigripes',
     'Standing BFC (8359398129).jpg'),
]

MAMIFEROS = [
    ('elefante', 'Elefante africano de sabana', 'African bush elephant', 'Loxodonta africana',
     '178 Male African bush elephant in Etosha National Park Photo by Giles Laurent.jpg'),
    ('rino-negro', 'Rinoceronte negro', 'Black rhinoceros', 'Diceros bicornis',
     'Black Rhino at Working with Wildlife.jpg'),
    ('rino-blanco', 'Rinoceronte blanco', 'White rhinoceros', 'Ceratotherium simum',
     '109 Male White rhinoceros walking in the Kalahari Desert of Namibia Photo by Giles Laurent.jpg'),
    ('jirafa', 'Jirafa angoleña', 'Angolan giraffe', 'Giraffa giraffa angolensis',
     '106 Angolan giraffe walking in the Kalahari Desert of Namibia Photo by Giles Laurent.jpg'),
    ('cebra-burchell', 'Cebra de Burchell', "Burchell's zebra", 'Equus quagga burchellii',
     'Equus quagga burchellii - Etosha, 2014.jpg'),
    ('orix', 'Órix o gemsbok', 'Gemsbok', 'Oryx gazella',
     'Gemsbok (Oryx gazella) male.jpg'),
    ('springbok', 'Springbok', 'Springbok', 'Antidorcas marsupialis',
     '174 Male Springbok in Etosha National Park Photo by Giles Laurent.jpg'),
    ('kudu', 'Gran kudú', 'Greater kudu', 'Tragelaphus strepsiceros',
     'Male greater kudu.jpg'),
    ('eland', 'Eland común', 'Common eland', 'Taurotragus oryx',
     'Taurotragus oryx - young bull - Etosha 2015.jpg'),
    ('nu', 'Ñu azul', 'Blue wildebeest', 'Connochaetes taurinus',
     'Wildebeest of Etosha National Park.jpg'),
    ('impala-cara-negra', 'Impala de cara negra', 'Black-faced impala', 'Aepyceros melampus petersi',
     'Impala (Aepyceros melampus) male Kruger.jpg'),
    ('dikdik', 'Dik-dik de Damara', 'Damara dik-dik', 'Madoqua damarensis',
     'Madoqua kirkii - male (Namutoni).jpg'),
    ('hiena-manchada', 'Hiena manchada', 'Spotted hyena', 'Crocuta crocuta',
     'Spotted hyena (Crocuta crocuta).jpg'),
    ('hiena-parda', 'Hiena parda', 'Brown hyena', 'Parahyaena brunnea',
     'Brown Hyena (Hyaena brunnea) leaving waterhole ... (50915531592), crop.jpg'),
    ('chacal', 'Chacal de lomo negro', 'Black-backed jackal', 'Lupulella mesomelas',
     '135 Black-backed jackal hunting for food at Cape cross Photo by Giles Laurent.jpg'),
    ('ratel', 'Ratel o tejón de la miel', 'Honey badger', 'Mellivora capensis',
     'Honey Badger.jpg'),
    ('facocero', 'Facóquero', 'Common warthog', 'Phacochoerus africanus',
     'Southern warthog (Phacochoerus africanus sundevallii) male.jpg'),
    ('hartebeest', 'Alcélafo rojo', 'Red hartebeest', 'Alcelaphus buselaphus caama',
     '2011-Red-Hartebeest.jpg'),
    ('steenbok', 'Steenbok', 'Steenbok', 'Raphicerus campestris',
     'Raphicerus campestris male (Etosha, 2012).jpg'),
    ('zorro-orejudo', 'Zorro orejudo', 'Bat-eared fox', 'Otocyon megalotis',
     'Otocyon megalotis - Etosha 2014.jpg'),
    ('jineta', 'Jineta de manchas pequeñas', 'Small-spotted genet', 'Genetta genetta',
     'A female common genet in the dining room, Satao Camp, Tsavo East.jpg'),
    ('puercoespin', 'Puercoespín del Cabo', 'Cape porcupine', 'Hystrix africaeaustralis',
     'Hystrix africaeaustralis Blijdorp Rotterdam.JPG'),
    ('liebre-saltadora', 'Liebre saltadora', 'Springhare', 'Pedetes capensis',
     'Spring Hare (Pedetes capensis) (6042009463).jpg'),
    ('klipspringer', 'Klipspringer o saltarrocas', 'Klipspringer', 'Oreotragus oreotragus',
     'Klipspringer.jpg'),
    ('mangosta-amarilla', 'Mangosta amarilla', 'Yellow mongoose', 'Cynictis penicillata',
     '082 Yellow mongoose in Khomas Region Photo by Giles Laurent.jpg'),
    ('babuino-chacma', 'Babuino chacma', 'Chacma baboon', 'Papio ursinus',
     'Chacma baboon (Papio ursinus griseipes) male head.jpg'),
    ('mangosta-rayada', 'Mangosta rayada', 'Banded mongoose', 'Mungos mungo',
     '168 Banded mongoose in Etosha National Park Photo by Giles Laurent.jpg'),
    ('zorro-del-cabo', 'Zorro del Cabo', 'Cape fox', 'Vulpes chama',
     'Vulpes chama (Etosha).jpg'),
    ('lobo-de-tierra', 'Lobo de tierra', 'Aardwolf', 'Proteles cristata',
     'Aardwolf, Namaqua National Park, South Africa 1.jpg'),
    ('ardilla-matorral', 'Ardilla de matorral de Smith', "Smith's bush squirrel", 'Paraxerus cepapi',
     'Tree squirrel, Etosha National Park, Namibia.jpg'),
    ('mangosta-esbelta', 'Mangosta esbelta', 'Slender mongoose', 'Galerella sanguinea',
     'Slender Mongoose Etosha National Park Namibia, crop.jpg'),
    # Vuelve el 29/08: salio del catalogo el 09/08 por vivir «en las lomas del extremo
    # oeste de Etosha», pero la ruta cambio y ahora pisa DOS sitios donde si esta —la
    # escarpa de Spreetshoogte (D2), donde la propia finca la anuncia (`11`), y
    # Damaraland (D8-D9)—. El reparto por regiones de `pais.py` lo mide.
    ('cebra-hartmann', 'Cebra de montaña de Hartmann', "Hartmann's mountain zebra",
     'Equus zebra hartmannae', 'Equus zebra hartmannae - Etosha 2015.jpg'),
    ('duiker-comun', 'Duiker común o cefalofo de Grimm', 'Common (grey) duiker',
     'Sylvicapra grimmia', 'Sylvicapra grimmia ssp. caffra.jpg'),
]

# Las rapaces, diurnas y nocturnas, tambien aparte desde el 15/08 y por el mismo motivo.
# Entran todas las que GBIF registra 10 o mas veces en oct-nov en alguna zona de la ruta
# (el umbral del propio metodo); las que se quedan por debajo se nombran en la intro.
RAPACES = [
    ('secretario', 'Secretario', 'Secretarybird', 'Sagittarius serpentarius',
     'Secretary bird Mara for WC.jpg'),
    ('aguila-marcial', 'Águila marcial', 'Martial eagle', 'Polemaetus bellicosus',
     'Martial eagle (Polemaetus bellicosus).jpg'),
    ('aguila-rapaz', 'Águila rapaz', 'Tawny eagle', 'Aquila rapax',
     '2012-tawny-eagle-0.jpg'),
    ('bateleur', 'Águila volatinera o bateleur', 'Bateleur', 'Terathopius ecaudatus',
     'Bataleur - Kruger National park (37161617713).jpg'),
    ('aguila-cafre', 'Águila cafre o de Verreaux', "Verreaux's eagle", 'Aquila verreauxii',
     "Verreaux's Eagle (Black Eagle), Aquila verreauxii, at Walter Sisulu National Botanical Garden, Gauteng, South Africa (28825016213).jpg"),
    ('aguila-azor-africana', 'Águila azor africana', 'African hawk-eagle', 'Aquila spilogaster',
     'Day 15 African Hawk-Eagle (Aquila spilogaster) (53235171227).jpg'),
    ('aguila-wahlberg', 'Águila de Wahlberg', "Wahlberg's eagle", 'Hieraaetus wahlbergi',
     "Wahlberg's Eagle (Hieraaetus wahlbergi) (46772007751).jpg"),
    ('aguila-calzada', 'Águila calzada', 'Booted eagle', 'Hieraaetus pennatus',
     'Booted eagle, Hieraaetus pennatus, at Kgalagadi 001 (32334023978).jpg'),
    ('aguila-pomerana', 'Águila pomerana', 'Lesser spotted eagle', 'Clanga pomarina',
     'Clanga pomarina, Belarus 1.jpg'),
    ('culebrera-pechinegra', 'Culebrera pechinegra', 'Black-chested snake eagle', 'Circaetus pectoralis',
     'Black-chested snake-eagle (Circaetus pectoralis).jpg'),
    ('culebrera-sombria', 'Culebrera sombría', 'Brown snake eagle', 'Circaetus cinereus',
     'Brown Snake Eagle (Circaetus cinereus) (39992020273).jpg'),
    ('pigargo-vocinglero', 'Pigargo vocinglero', 'African fish eagle', 'Icthyophaga vocifer',
     'African fish eagle, Haliaeetus vocifer, at Chobe National Park, Botswana (33516612831).jpg'),
    ('aguila-pescadora', 'Águila pescadora', 'Osprey', 'Pandion haliaetus',
     'Balbuzard pecheur Lac de Tunis.jpg'),
    ('buitre-dorsiblanco', 'Buitre dorsiblanco africano', 'White-backed vulture', 'Gyps africanus',
     '2012-white-backed-vulture.jpg'),
    ('buitre-orejudo', 'Buitre orejudo', 'Lappet-faced vulture', 'Torgos tracheliotos',
     '2012-lappet-faced-vulture.jpg'),
    ('buitre-cabeciblanco', 'Buitre cabeciblanco', 'White-headed vulture', 'Trigonoceps occipitalis',
     'Day 12 White-headed Vulture (Trigonoceps occipitalis) (53439819016).jpg'),
    ('azor-lagartijero', 'Azor lagartijero claro', 'Pale chanting goshawk', 'Melierax canorus',
     'Melierax canorus-01.jpg'),
    ('gavilan-gabar', 'Gavilán gabar', 'Gabar goshawk', 'Micronisus gabar',
     'Gabar Goshawk (Micronisus gabar).jpg'),
    ('gavilan-chikra', 'Gavilán chikra', 'Shikra (little banded goshawk)', 'Accipiter badius',
     'Little Banded Goshawk - Accipiter badius, Port Edward, Kwazulu-Natal, South Africa.jpg'),
    ('aguilucho-caricalvo', 'Aguilucho caricalvo común', 'African harrier-hawk (gymnogene)', 'Polyboroides typus',
     'African harrier-hawk (Polyboroides typus typus) taking off, crop.jpg'),
    ('aguilucho-papialbo', 'Aguilucho papialbo', 'Pallid harrier', 'Circus macrourus',
     'Pallid harrier.jpg'),
    ('aguilucho-cenizo', 'Aguilucho cenizo', "Montagu's harrier", 'Circus pygargus',
     "Montagu's Harrier Male (Circus pygargus) at Velavadar National Park, Gujarat, India DSCN7503 02.jpg"),
    ('elanio', 'Elanio común', 'Black-winged (black-shouldered) kite', 'Elanus caeruleus',
     'Black-shouldered kite (Elanus caeruleus caeruleus) young adult.jpg'),
    ('milano-negro', 'Milano negro', 'Black kite / yellow-billed kite', 'Milvus migrans',
     'Black Kite in Rabindra Sarobar January 2024 by Tisha Mukherjee 02.jpg'),
    ('busardo-ratonero', 'Busardo ratonero (ratonero estepario)', 'Steppe buzzard', 'Buteo buteo',
     'Buteo buteo vulpinus (World of Birds, South Africa)2.jpg'),
    ('busardo-augur', 'Busardo augur', 'Augur buzzard', 'Buteo augur',
     '009 Augur buzzard in flight in the Ngorongoro Crater Photo by Giles Laurent.jpg'),
    ('busardo-augur-meridional', 'Busardo augur meridional', 'Jackal buzzard', 'Buteo rufofuscus',
     'Jackal buzzard, Buteo rufofuscus, at Kgalagadi Transfrontier Park, Northern Cape, South Africa (34676042615) (cropped).jpg'),
    ('cernicalo-ojiblanco', 'Cernícalo ojiblanco', 'Greater kestrel', 'Falco rupicoloides',
     'Falco rupicoloides -Etosha National Park, Namibia-8.jpg'),
    ('cernicalo-africano', 'Cernícalo africano o roquero', 'Rock kestrel', 'Falco rupicolus',
     'Rock Kestrel (Falco rupicolis) (32496132591).jpg'),
    ('alcotan-turumti', 'Alcotán turumti', 'Red-necked falcon', 'Falco chicquera',
     'Falco chicquera (Etosha, 2012).jpg'),
    ('halcon-borni', 'Halcón borní', 'Lanner falcon', 'Falco biarmicus',
     'Lanner Falcon Falco biarmicus, Kgalagadi Transfrontier Park, Northern Cape, South Africa. (34514634415).jpg'),
    ('halcon-peregrino', 'Halcón peregrino', 'Peregrine falcon', 'Falco peregrinus',
     'Falco peregrinus minor, Cape Town, South Africa 118534019.jpg'),
    ('halconcito-africano', 'Halconcito africano', 'Pygmy falcon', 'Polihierax semitorquatus',
     'Pygmy Falcon (Polihierax semitorquatus), at Kgalagadi Transfrontier Park, Northern Cape, South Africa (34384165391).jpg'),
    ('buho-lacteo', 'Búho lácteo de Verreaux', "Verreaux's eagle-owl", 'Bubo lacteus',
     '2012-giant-eagle-owl.jpg'),
    ('buho-manchado', 'Búho manchado', 'Spotted eagle-owl', 'Bubo africanus',
     'Spotted Eagle-Owl RWD.jpg'),
    ('autillo-africano', 'Autillo africano', 'African scops owl', 'Otus senegalensis',
     'African-scops owl (Otus senegalensis) male.jpg'),
    ('autillo-cariblanco', 'Autillo cariblanco sureño', 'Southern white-faced owl', 'Ptilopsis granti',
     'Ptilopsis granti-Chobe River front, Botswana-8.jpg'),
    ('mochuelo-perlado', 'Mochuelo perlado', 'Pearl-spotted owlet', 'Glaucidium perlatum',
     'Pearl-spotted owlet (Glaucidium perlatum diurnum).jpg'),
    ('lechuza-comun', 'Lechuza común', 'Barn owl', 'Tyto alba',
     'Tyto alba affinis, Oshana Region, Namibia.jpg'),
    ('buho-moro', 'Búho moro', 'Marsh owl', 'Asio capensis',
     'Asio capensis 261246078.jpg'),
]

AVES = [
    ('avestruz', 'Avestruz común', 'Common ostrich', 'Struthio camelus',
     'Struthio camelus - Etosha 2014 (3).jpg'),
    ('avutarda-kori', 'Avutarda kori', 'Kori bustard', 'Ardeotis kori',
     'Kori bustard (Ardeotis kori kori) male.jpg'),
    ('carraca-lila', 'Carraca lila', 'Lilac-breasted roller', 'Coracias caudatus',
     '143 Lilac-breasted roller in Etosha National Park Photo by Giles Laurent.jpg'),
    ('calao-amarillo', 'Cálao de pico amarillo sureño', 'Southern yellow-billed hornbill', 'Tockus leucomelas',
     '155 Southern yellow-billed hornbill in Etosha National Park Photo by Giles Laurent.jpg'),
    ('calao-rojo', 'Cálao de pico rojo sureño', 'Southern red-billed hornbill', 'Tockus rufirostris',
     'Southern red-billed hornbill (Tockus rufirostris) male, crop.jpg'),
    ('tejedor-republicano', 'Tejedor republicano', 'Sociable weaver', 'Philetairus socius',
     'Sociable weaver (Philetairus socius).jpg'),
    ('flamenco-enano', 'Flamenco enano', 'Lesser flamingo', 'Phoeniconaias minor',
     'Flock of Lesser Flamingo along with juvenile near Jamnagar railway stationDSCN1798 1.jpg'),
    # Estaba en la parte 2 hasta que se miro el dato: GBIF le da 18 registros de
    # octubre-noviembre DENTRO del poligono de Etosha, mas que muchas fichas de la ruta.
    # No es del Zambeze solamente; aqui tambien cria. Se mueve donde toca.
    ('grulla-carunculada', 'Grulla carunculada', 'Wattled crane', 'Bugeranus carunculatus',
     'Grus carunculata, Linyanti, Caprivi, Namibia 1.jpg'),
    ('grulla-azul', 'Grulla azul', 'Blue crane', 'Grus paradisea',
     'Grus paradisea Etosha 1.jpg'),
    ('ganga-namaqua', 'Ganga namaqua', 'Namaqua sandgrouse', 'Pterocles namaqua',
     '2012-namaqua-sandgrouse-male.jpg'),
    ('sison-negro', 'Sisón negro norteño', 'Northern black korhaan', 'Afrotis afraoides',
     'Northern black korhaan (Afrotis afraoides) male.jpg'),
    ('alcaudon-carmesi', 'Alcaudón de pecho carmesí', 'Crimson-breasted shrike', 'Laniarius atrococcineus',
     '161 Crimson-breasted shrike in Otjozondjupa Region Photo by Giles Laurent.jpg'),
    ('abejaruco-europeo', 'Abejaruco europeo', 'European bee-eater', 'Merops apiaster',
     'Bee-eater (19270331108).jpg'),
    ('ciguena-abdim', 'Cigüeña de Abdim', "Abdim's stork", 'Ciconia abdimii',
     'Ciconia abdimii -London Zoo-8a.jpg'),
    ('estornino-cabo', 'Estornino brillante del Cabo', 'Cape starling', 'Lamprotornis nitens',
     '159 Cape starling in Etosha National Park Photo by Giles Laurent.jpg'),
    ('pelicano', 'Pelícano blanco común', 'Great white pelican', 'Pelecanus onocrotalus',
     'Great white pelican (Pelecanus onocrotalus).jpg'),
    ('flamenco-comun', 'Flamenco común', 'Greater flamingo', 'Phoenicopterus roseus',
     '010 Greater flamingos male and female in the Camargue during mating season Photo by Giles Laurent.jpg'),
    ('cormoran-cabo', 'Cormorán del Cabo', 'Cape cormorant', 'Phalacrocorax capensis',
     'Phalacrocorax capensis - Namib 2013.jpg'),
    ('charran-damara', 'Charrán damara', 'Damara tern', 'Sternula balaenarum',
     'Damara Tern (8077271589).jpg'),
    ('ostrero-africano', 'Ostrero africano', 'African oystercatcher', 'Haematopus moquini',
     'African Black Oystercatcher (2).JPG'),
    ('gaviota-hartlaub', 'Gaviota de Hartlaub', "Hartlaub's gull", 'Chroicocephalus hartlaubii',
     'Gaviota de Hartlaub (Chroicocephalus hartlaubii), Walvis Bay, Namibia, 2018-08-05, DD 31.jpg'),
    ('avoceta', 'Avoceta común', 'Pied avocet', 'Recurvirostra avosetta',
     'Pied Avocet at Walvis Bay, Namibia.jpg'),
    ('francolin-picorrojo', 'Francolín de pico rojo', 'Red-billed spurfowl', 'Pternistis adspersus',
     '2011-red-billed-francolin.jpg'),
    ('avefria-armada', 'Avefría armada', 'Blacksmith lapwing', 'Vanellus armatus',
     'Vanellus armatus - Etosha 2014.jpg'),
    ('drongo', 'Drongo ahorquillado', 'Fork-tailed drongo', 'Dicrurus adsimilis',
     'Dicrurus adsimilis, Namibia (144258501).jpg'),
    ('pintada', 'Pintada común', 'Helmeted guineafowl', 'Numida meleagris',
     'Numida meleagris -Etosha National Park, Namibia-8.jpg'),
    ('quelea', 'Quélea común', 'Red-billed quelea', 'Quelea quelea',
     'Red-billed Queleas (Quelea quelea) (6040852957).jpg'),
    ('turaco-unicolor', 'Turaco unicolor', 'Grey go-away-bird', 'Corythaixoides concolor',
     'Grey go-away-bird (Corythaixoides concolor pallidiceps).jpg'),
    ('toco-piquinegro', 'Toco piquinegro', 'African grey hornbill', 'Lophoceros nasutus',
     'African Grey Hornbill (Lophoceros nasutus epirhinus) female.jpg'),
    ('bulbul-encapuchado', 'Bulbul encapuchado', 'African red-eyed bulbul', 'Pycnonotus nigricans',
     '127 African red-eyed bulbul in Namib-Naukluft National Park Photo by Giles Laurent.jpg'),
    ('turdoide-caricalvo', 'Turdoide caricalvo', 'Bare-cheeked babbler', 'Turdoides gymnogenys',
     'Bare-cheeked Babbler.jpg'),
    ('charran-comun', 'Charrán común', 'Common tern', 'Sterna hirundo',
     'Sterna hirundo -Bojuru, Rio Grande do Sul, Brasil-8.jpg'),
    ('gaviota-cocinera', 'Gaviota cocinera', 'Kelp gull', 'Larus dominicanus',
     'Cape (kelp) gull-3327 - Flickr - Ragnhild & Neil Crawford.jpg'),
    ('estornino-naburup', 'Estornino Naburup', 'Pale-winged starling', 'Onychognathus nabouroup',
     '142 Pale-winged starling in Twyfelfontein Photo by Giles Laurent.jpg'),
    ('sison-damara', 'Sisón de Damaraland', "Rüppell's korhaan", 'Heterotetrax rueppelii',
     "Rüppell's korhaan (Eupodotis rueppellii rueppellii) male.jpg"),
    ('avutarda-namibia', 'Avutarda de Namibia', "Ludwig's bustard", 'Neotis ludwigii',
     'Neotis ludwigii.jpg'),
    ('alondra-dunas', 'Alondra de las dunas', 'Dune lark', 'Calendulauda erythrochlamys',
     'Dune lark-3947 - Flickr - Ragnhild & Neil Crawford.jpg'),
    ('lorito-ruppell', 'Lorito de Rüppell', "Rüppell's parrot", 'Poicephalus rueppellii',
     "Rüppell's parrot (Poicephalus rueppellii) female.jpg"),
    ('toco-angoleno', 'Toco angoleño', "Monteiro's hornbill", 'Tockus monteiri',
     'Tockus monteiri (606), crop.jpg'),
    ('inseparable-namibia', 'Inseparable de Namibia', 'Rosy-faced lovebird', 'Agapornis roseicollis',
     '087 Rosy-faced lovebird couple cuddling in Damaraland Photo by Giles Laurent.jpg'),
    # Los casi endemicos del oeste, anadidos el 29/08 con el barrido de todo el pais:
    # pajaros que practicamente solo existen en Namibia y el suroeste de Angola y que
    # caen en el trozo de ruta de la escarpa, Erongo y Damaraland.
    ('cantor-de-roca', 'Cantor de roca o rockrunner', 'Rockrunner', 'Achaetops pycnopygius',
     'Rockrunner 143ND500 DSC0869.jpg'),
    ('papamoscas-herero', 'Papamoscas herero', 'Herero chat', 'Namibornis herero',
     'Namibornis herero K1.jpg'),
    ('alcaudon-colablanca', 'Alcaudón de cola blanca', 'White-tailed shrike',
     'Lanioturdus torquatus', 'White-tailed Shrike 143ND500 DSC0729.jpg'),
    ('francolin-hartlaub', 'Francolín de Hartlaub', "Hartlaub's spurfowl",
     'Pternistis hartlaubi', 'Hartlaub-s Spurfowl 143ND500 DSC0583.jpg'),
    ('carbonero-carp', 'Carbonero de Carp', "Carp's tit", 'Melaniparus carpi',
     "Carp's Tit (Melaniparus carpi) in Namibia.jpg"),
    ('alondra-gray', 'Alondra de Gray', "Gray's lark", 'Ammomanopsis grayi',
     "Gray's lark -4770 - Flickr - Ragnhild & Neil Crawford.jpg"),
]

REPTILES = [
    ('vibora-bufadora', 'Víbora bufadora', 'Puff adder', 'Bitis arietans',
     'Bitis arietans by Danny S. 1.JPG'),
    ('cobra-cebra', 'Cobra escupidora cebra', 'Zebra spitting cobra', 'Naja nigricincta',
     'Naja nigricincta nigricincta.jpg'),
    ('mamba-negra', 'Mamba negra', 'Black mamba', 'Dendroaspis polylepis',
     'Dendroaspis polylepis (14).jpg'),
    ('vibora-peringuey', 'Víbora de Péringuey', "Peringuey's adder", 'Bitis peringueyi',
     'Namibian Sidewinder Bitis peringueyi.jpg'),
    ('vibora-cornuda', 'Víbora cornuda', 'Horned adder', 'Bitis caudalis',
     'Bitis caudalis00a.jpg'),
    ('camaleon-namib', 'Camaleón del Namib', 'Namaqua chameleon', 'Chamaeleo namaquensis',
     'Chamaeleo namaquensis (Walvis Bay).jpg'),
    ('gecko-palmato', 'Gecko palmeado del Namib', 'Web-footed gecko', 'Pachydactylus rangei',
     'Pachydactylus-rangei.jpg'),
    ('agama-namibia', 'Agama de roca de Namibia', 'Namibian rock agama', 'Agama planiceps',
     'Namib rock agama (Agama planiceps) male.jpg'),
    ('varano-roca', 'Varano de roca', 'Rock monitor', 'Varanus albigularis',
     'White-throated Monitor (Varanus albigularis) (32184691034).jpg'),
    ('tortuga-leopardo', 'Tortuga leopardo', 'Leopard tortoise', 'Stigmochelys pardalis',
     'Leopard Tortoise (Stigmochelys pardalis) (17331907085).jpg'),
    ('lagarto-pala', 'Lagarto de nariz de pala', 'Shovel-snouted lizard', 'Meroles anchietae',
     'Meroles anchietae 345390261.jpg'),
    ('escinco-arboricola', 'Escinco arborícola del Kalahari', 'Kalahari tree skink', 'Trachylepis spilogaster',
     'Trachylepis spilogaster in South Africa 118136825.jpg'),
    ('gecko-fischer', 'Gecko de Fischer', "Fischer's thick-toed gecko", 'Chondrodactylus laevigatus',
     'Chondrodactylus-laevigatus.jpg'),
    ('galapago-africano', 'Galápago africano o tortuga de escudo', 'African helmeted turtle', 'Pelomedusa subrufa',
     'Pelomedusa subrufa 188270144.jpg'),
    ('gecko-diurno', 'Gecko diurno del Namib', 'Namib day gecko', 'Rhoptropus afer',
     'Rhoptropus afer 345390145.jpg'),
    ('lagarto-cuna', 'Lagarto de nariz de cuña', 'Wedge-snouted sand lizard', 'Meroles cuneirostris',
     'Meroles cuneirostris 345390278.jpg'),
    ('gecko-suelo-gigante', 'Gecko gigante del suelo', 'Giant ground gecko',
     'Chondrodactylus angulifer', 'Giant Ground Gecko (Chondrodactylus angulifer) (31145329777).jpg'),
]

COSTA = [
    ('lobo-marino', 'Lobo marino del Cabo', 'Cape fur seal', 'Arctocephalus pusillus',
     'Arctocephalus pusillus - SE Tasmania.jpg'),
    ('delfin-heaviside', 'Delfín de Heaviside', "Heaviside's dolphin", 'Cephalorhynchus heavisidii',
     'Dolphins at Lüderitz, Namibia (3144863196).jpg'),
    ('delfin-mular', 'Delfín mular', 'Bottlenose dolphin', 'Tursiops truncatus',
     '010 Atlantic bottlenose dolphin jumping at Pelican point Photo by Giles Laurent.jpg'),
    ('ballena-jorobada', 'Ballena jorobada', 'Humpback whale', 'Megaptera novaeangliae',
     '001 Humpback whale breaching in Ballena Marine National Park Photo by Giles Laurent.jpg'),
    ('daman', 'Damán roquero', 'Rock hyrax', 'Procavia capensis',
     'Rock hyrax Serengeti National Park.jpg'),
    ('rata-dassie', 'Rata dassie o rata de las rocas', 'Dassie rat', 'Petromus typicus',
     '141 Dassie rat in Twyfelfontein Photo by Giles Laurent.jpg'),
    ('ardilla-terrestre', 'Ardilla terrestre del Cabo', 'Cape ground squirrel', 'Xerus inauris',
     'Cape ground squirrel, Xerus inauris, at Krugersdorp Game Reserve, Gauteng, South Africa (27410204561).jpg'),
    # GBIF los sitúa en la caja de la costa de la ruta —Walvis Bay y Swakopmund—, así
    # que van aquí y no en la parte de «el resto del país»: el alcatraz con 228 registros
    # de oct-nov y el cormorán de las bancas con 65 no son una rareza de Lüderitz.
    ('pinguino-africano', 'Pingüino africano', 'African penguin', 'Spheniscus demersus',
     'Pingüino de El Cabo (Spheniscus demersus), Playa de Boulders, Simon\'s Town, Sudáfrica, 2018-07-23, DD 11.jpg'),
    ('alcatraz-cabo', 'Alcatraz del Cabo', 'Cape gannet', 'Morus capensis',
     'Cape gannet (Morus capensis) sideview.jpg'),
    ('cormoran-bancas', 'Cormorán de las bancas', 'Bank cormorant', 'Phalacrocorax neglectus',
     'Bank Cormorant (Phalacrocorax neglectus) (32414152818).jpg'),
    ('ballena-franca', 'Ballena franca austral', 'Southern right whale', 'Eubalaena australis',
     'Eubalaena australis 98405964.jpg'),
]

BICHOS = [
    ('escarabajo-niebla', 'Escarabajo de la niebla', 'Fog-basking beetle', 'Onymacris unguicularis',
     'Onymacris unguicularis (Sudan).jpg'),
    ('escorpion', 'Escorpión de cola gruesa', 'Black hairy thick-tailed scorpion', 'Parabuthus villosus',
     'Parabuthus villosus.jpg'),
    ('arana-rueda', 'Araña blanca del Namib', 'Dancing white lady spider', 'Leucorchestris arenicola',
     'Leucorchestris arenicola.jpg'),
    ('termita', 'Termita constructora', 'Termite', 'Macrotermes michaelseni',
     'Macrotermes michaelseni.jpg'),
    ('escarabajo-pelotero', 'Escarabajo pelotero', 'Dung beetle', 'Scarabaeus satyrus',
     'Scarabaeus satyrus (Boheman, 1860) (3847992837) (2).jpg'),
    ('solifugo', 'Solífugo o araña camello', 'Sun spider / camel spider', 'Solifugae',
     'Solifuge in Trinidad, Colorado, July 2026.jpg'),
    ('gusano-mopane', 'Gusano de mopane', 'Mopane worm', 'Gonimbrasia belina',
     'Colophospermum mopane 50D 0486.jpg'),
    ('shongololo', 'Milpiés gigante o shongololo', 'Giant African millipede', 'Archispirostreptus gigas',
     'Archispirostreptus-Gigas-Amphitheatre.jpg'),
    ('anofeles', 'Mosquito anofeles', 'Anopheles mosquito', 'Anopheles',
     'Anopheles stephensi.jpeg'),
]

# ---------------------------------------------------------------------------
# La Namibia que este viaje NO pisa. Anadido el 29/08/2026.
#
# El resto del catalogo son animales de la ruta y llevan su porcentaje de avistamiento
# medido. Estas tres listas son lo contrario: fauna que existe en el pais y que **con
# este itinerario no se va a ver**, con el sitio al que habria que ir a buscarla. Van
# en una parte aparte de la guia y con esa etiqueta, para que ni una ficha de aqui se
# confunda con una expectativa del viaje.
# ---------------------------------------------------------------------------

NORTE = [
    ('hipopotamo', 'Hipopótamo', 'Hippopotamus', 'Hippopotamus amphibius',
     'Hipopótamo (Hippopotamus amphibius), parque nacional de Chobe, Botsuana, 2018-07-28, DD 82.jpg'),
    ('cocodrilo-nilo', 'Cocodrilo del Nilo', 'Nile crocodile', 'Crocodylus niloticus',
     'Nile crocodile in the Zambezi.jpg'),
    ('bufalo-cafre', 'Búfalo cafre', 'African buffalo', 'Syncerus caffer',
     'African buffalo (Syncerus caffer caffer) male with cattle egret.jpg'),
    ('licaon', 'Licaón o perro salvaje africano', 'African wild dog', 'Lycaon pictus',
     'African wild dog (Lycaon pictus pictus).jpg'),
    ('sable', 'Antílope sable', 'Sable antelope', 'Hippotragus niger',
     'Sable antelope (Hippotragus niger) adult male.jpg'),
    ('roan', 'Antílope ruano', 'Roan antelope', 'Hippotragus equinus',
     'Roan antelope (Hippotragus equinus) male walking.jpg'),
    ('antilope-acuatico', 'Antílope acuático o waterbuck', 'Waterbuck', 'Kobus ellipsiprymnus',
     'Antílope acuático (Kobus ellipsiprymnus), parque nacional de Chobe, Botsuana, 2018-07-28, DD 49.jpg'),
    ('lechwe-rojo', 'Lechwe rojo', 'Red lechwe', 'Kobus leche',
     'Red lechwe (Kobus leche leche) male.jpg'),
    ('puku', 'Puku', 'Puku', 'Kobus vardonii',
     'Kobus vardonii b.jpg'),
    ('sitatunga', 'Sitatunga', 'Sitatunga', 'Tragelaphus spekii',
     'Sitatunga (1).JPG'),
    ('tsessebe', 'Tsessebe', 'Tsessebe', 'Damaliscus lunatus',
     'Tsessebe (Botswana).jpg'),
    ('antilope-jeroglifico', 'Antílope jeroglífico o bushbuck', 'Bushbuck',
     'Tragelaphus sylvaticus', 'Cape bushbuck (Tragelaphus sylvaticus) female.jpg'),
    ('mono-vervet', 'Mono vervet o cercopiteco verde', 'Vervet monkey',
     'Chlorocebus pygerythrus',
     'Chlorocebus pygerythrus.jpg'),
    ('nutria-cuellomanchado', 'Nutria de cuello manchado', 'Spotted-necked otter',
     'Hydrictis maculicollis', 'Spot-necked Otter (8379813628).jpg'),
    ('nutria-cabo', 'Nutria del Cabo', 'African clawless otter', 'Aonyx capensis',
     'Aonyx capensis, male, Shamvura.jpg'),
    ('abejaruco-carmesi', 'Abejaruco carmesí sureño', 'Southern carmine bee-eater',
     'Merops nubicoides', 'Merops nubicoides, Kasane, Botswana 1.jpg'),
    ('picotijera-africano', 'Picotijera africano', 'African skimmer', 'Rynchops flavirostris',
     'African skimmer in Chobe National Park 01.jpg'),
    ('buho-pescador-pel', 'Búho pescador de Pel', "Pel's fishing owl", 'Scotopelia peli',
     "Pel's Fishing-Owl - Malawi.jpg"),
    ('garceta-vinosa', 'Garceta vinosa', 'Slaty egret', 'Egretta vinaceigula',
     'Slaty egret, Egretta vinaceigula, Chobe National Park, Botswana. (32278292746).jpg'),
    ('piton-roca', 'Pitón de roca sudafricana', 'Southern African rock python',
     'Python natalensis', 'Southern African Python (Python natalensis) juvenile (6046152898).jpg'),
]

KALAHARI = [
    ('suricata', 'Suricata', 'Meerkat', 'Suricata suricatta',
     '112 Meerkat standing in the Kalahari Desert of Namibia Photo by Giles Laurent.jpg'),
    ('oricteropo', 'Oricteropo o cerdo hormiguero', 'Aardvark', 'Orycteropus afer',
     'Orycteropus afer 175359469.jpg'),
    ('pangolin', 'Pangolín de Temminck', 'Temminck\'s ground pangolin', 'Smutsia temminckii',
     '20150808 Schuppentier am Waterberg.jpg'),
    ('piton-anchieta', 'Pitón de Anchieta', "Anchieta's dwarf python", 'Python anchietae',
     'Python anchietae (1).jpg'),
]

GRUPOS_FAUNA = [
    ('felino', 'Felinos', FELINOS),
    ('mamifero', 'Mamíferos', MAMIFEROS),
    ('rapaz', 'Aves rapaces', RAPACES),
    ('ave', 'Aves', AVES),
    ('reptil', 'Reptiles', REPTILES),
    ('costa', 'La costa, la roca y la arena', COSTA),
    ('bicho', 'Bichos', BICHOS),
    # La parte 2 de la guia: lo que hay en Namibia y este viaje no pisa.
    ('norte', 'El norte húmedo: el Zambeze, el Okavango y el Kunene', NORTE),
    ('kalahari', 'El Kalahari, el sur y lo que casi nadie ve', KALAHARI),
]
