# Texto de identificacion por especie (rasgos morfologicos, no cifras sin fuente).
# La linea "donde y cuando en Etosha" se rellena aparte, con fuente.

ID = {
 # --- MAMIFEROS ---
 "elefante": "El mayor animal terrestre. Orejas enormes con forma de África y dos «dedos» en la punta de la trompa. Los de Etosha se ven blanquecinos: se rebozan en el polvo calcáreo del pan.",
 "rino-negro": "El labio superior es **puntiagudo y prensil** —ramonea arbustos—, la cabeza va alta y lleva dos cuernos. Solitario y de genio corto. Se distingue del blanco por el labio, nunca por el color.",
 "rino-blanco": "Labio **ancho y cuadrado** para pacer hierba, cabeza baja y joroba en la nuca. Más grande y más sociable que el negro. Lo de «blanco» viene de *wijd* (ancho) en afrikáans.",
 "leon": "Melena en el macho, pardo uniforme. Con calor pasa el día tumbado a la sombra: la actividad es al alba, al anochecer y de noche.",
 "leopardo": "Rosetas **sin punto central**, cuerpo bajo y macizo, cola larguísima. Nocturno y arborícola: el más difícil de ver de los grandes.",
 "guepardo": "Manchas **simples**, no rosetas, y dos «lágrimas» negras del ojo a la boca. Silueta esbelta de galgo con cabeza pequeña. Caza de día, a plena luz.",
 "jirafa": "La subespecie del suroeste, de manchas irregulares que se desvanecen hacia las patas. Al beber tiene que abrir las patas en compás: su momento más vulnerable, y el mejor para la foto.",
 "cebra-burchell": "La cebra de llanura: rayas **anchas** que siguen hasta la barriga, con «rayas de sombra» pardas intercaladas. Es la que forma manadas en las charcas.",
 "orix": "Cuernos rectos como lanzas —en el macho y en la hembra— y máscara facial en blanco y negro. Aguanta sin beber; es el emblema del país y sale en el escudo de Namibia.",
 "springbok": "Banda castaña que separa el lomo del vientre blanco, y una cresta de pelo blanco en la grupa que abre al saltar. Da botes rígidos con el lomo arqueado: el *pronking*.",
 "kudu": "El macho lleva cuernos en espiral y una uve blanca entre los ojos; el costado, rayas verticales finas. **Salta vallas altísimas: es el gran peligro de la carretera al anochecer.**",
 "eland": "El antílope más grande y pesado, de aspecto casi bovino: papada colgante y cuernos rectos con una espiral en la base.",
 "nu": "Morro cuadrado, crin y barba oscuras, cuernos que bajan y vuelven a subir. Silueta desconcertante: toro por delante, caballo por detrás.",
 "impala-cara-negra": "**Subespecie endémica** del noroeste de Namibia y el suroeste de Angola: como la impala común, pero con una franja negra bien marcada en la cara. Escasa y protegida.",
 "dikdik": "Antílope diminuto, a la altura de la rodilla, con trompita móvil y un penacho de pelo en la frente. Casi siempre en pareja y pegado al monte espeso.",
 "hiena-manchada": "Pelaje moteado, cuello grueso, **orejas redondas** y lomo caído hacia atrás. Es la que se oye de noche desde la tienda.",
 "hiena-parda": "Melena larga y desgreñada de pelo oscuro y **orejas puntiagudas**. Mucho más rara y esquiva que la manchada; verla es un premio.",
 "chacal": "La «silla de montar» negra y plateada sobre el lomo, y orejas grandes. Omnipresente en las charcas y desvergonzado en los campamentos.",
 "ratel": "Manto gris claro desde la cabeza hasta la cola sobre cuerpo negro. Pequeño, bajo, y con una fama de temerario que se ha ganado a pulso.",
 "facocero": "Verrugas en la cara y colmillos curvos hacia arriba. Corre con la cola tiesa como una antena y **se arrodilla sobre los codos** para pacer.",
 "hartebeest": "Cara larguísima y estrecha, cuernos en forma de arpa montados sobre un pedúnculo, y grupa muy caída. Color rojizo brillante al sol.",
 "steenbok": "Pequeño, rojizo y con orejas enormes; solo el macho lleva cuernos, cortos y rectos. Se queda clavado mirándote y sale disparado en zigzag.",
 # --- AVES ---
 "avestruz": "El ave más grande del mundo. El macho, negro y blanco; la hembra, parda. En Etosha se ven cruzando la llanura abierta.",
 "avutarda-kori": "Una de las aves voladoras más pesadas que existen. Camina por la llanura con paso solemne; en exhibición el macho hincha el cuello como un globo blanco.",
 "secretario": "Rapaz de patas larguísimas que **caza andando** y mata serpientes a pisotones. Las plumas negras de la nuca le dan el nombre, como plumas de escribiente tras la oreja.",
 "carraca-lila": "La postal de África: pecho lila, garganta azul y alas turquesa que estallan al volar. Se posa a la vista, en un poste o una rama seca.",
 "calao-amarillo": "Pico grande, curvo y **amarillo**. Confiado y muy presente en los campamentos, donde vigila las mesas del desayuno.",
 "calao-rojo": "Idéntico en forma al anterior, pero con el pico **rojo**. Y ojo: aquí «cálao rojo» son DOS especies casi gemelas que conviven en el eje — **ojo amarillo** = el sureño (esta ficha); **ojo oscuro y cara blanca** = el cálao damara, casi endémico. Hacia Namutoni, mayoría de sureños.",
 "tejedor-republicano": "Se ve **el nido antes que el pájaro**: pajares colectivos gigantes que engullen un árbol o un poste de la luz y que ocupan generaciones enteras. *(Los nidos pequeños, esféricos y colgantes de los árboles de los campamentos son de otro: el tejedor enmascarado.)*",
 "aguila-marcial": "La mayor águila de África: capucha oscura y pecho blanco moteado. Suele estar posada, inmóvil, en lo alto de una acacia.",
 "buitre-dorsiblanco": "El buitre común de la sabana. El dorso pálido que le da nombre solo se le ve bien en vuelo.",
 "flamenco-enano": "Más pequeño y más intensamente rosa que el común, con el pico oscuro de lejos. Todo depende de que haya agua: sin pan inundada, no hay flamencos.",
 "grulla-azul": "Gris azulada, con la cabeza abultada y unas largas plumas alares que arrastra como una cola. Elegantísima y, aquí, rareza.",
 "ganga-namaqua": "Cola muy puntiaguda; llega a las charcas en bandos y a horas fijas. El macho **empapa las plumas del vientre** para llevarles agua a los pollos.",
 "sison-negro": "El macho es negro con grandes parches blancos en el ala; se delata con un chillido metálico al levantar el vuelo.",
 "azor-lagartijero": "Gris claro, con patas y cera del pico **rojas** y **obispillo blanco**. Casi siempre posado en un poste, oteando el suelo: la rapaz más registrada de toda la ruta. *(Su hermano oscuro, el azor lagartijero oscuro, de gris más plomizo y obispillo barrado, asoma por el este de Etosha con 9 registros en oct-nov — por debajo del umbral, sin ficha.)*",
 "alcaudon-carmesi": "Negro por arriba y **rojo intenso** por abajo: imposible de confundir. Se mueve por dentro del matorral espeso.",
 "buho-lacteo": "El búho más grande de África, con **párpados rosados** que se le ven al parpadear. En los árboles grandes de los campamentos.",
 "abejaruco-europeo": "El mismo que cría en España y pasa aquí el invierno nuestro: verde, castaño y amarillo, con antifaz negro. Caza al vuelo desde una rama seca y vuelve al mismo posadero.",
 "ciguena-abdim": "Cigüeña pequeña y oscura, de patas grises con las «rodillas» rojas. La llaman la cigüeña de la lluvia porque sigue a los frentes — aquí eso significa **bien entrada la temporada**, no noviembre.",
 "estornino-cabo": "Azul verdoso metálico con el ojo naranja. En los campamentos, siempre atento a las migas de la mesa.",
 "pigargo-vocinglero": "Cabeza blanca y pecho castaño; su reclamo es, literalmente, el sonido de África. Necesita agua abierta, así que aquí depende del pan y de las charcas grandes.",

 # --- REPTILES ---
 "vibora-bufadora": "Gruesa, corta y con galones en uve por el lomo. **No huye: se queda quieta confiando en su camuflaje**, y de ahí que se le atribuyan la mayoría de mordeduras graves del continente. Mira dónde pisas al anochecer y nada de andar descalzo por el campamento.",
 "cobra-cebra": "Del suroeste africano, con bandas oscuras. **Escupe el veneno a los ojos** a varios metros y con puntería. Si levanta el cuerpo y abre la capucha, retrocede despacio: nunca la acorrales.",
 "mamba-negra": "Larga, delgada y **gris oliva** —lo negro es el interior de la boca, no la piel—. Rapidísima y nerviosa, pero esquiva: lo normal es no verla. La peor fama de África, y en buena parte merecida.",
 "vibora-peringuey": "Diminuta, de la arena del Namib. **Se entierra dejando fuera solo los ojos** y se desplaza de lado. Suya es la huella en zigzag que aparece en las dunas por la mañana.",
 "vibora-cornuda": "Un «cuerno» escamoso sobre cada ojo. Se entierra en la arena o la grava del desierto y espera. Pequeña, pero con veneno de verdad.",
 "camaleon-namib": "El camaleón que **corre por el suelo del desierto** en vez de trepar. Cambia de color para regular su temperatura: oscuro de mañana para calentarse, pálido al mediodía. La estrella de los tours de «desierto vivo» de Swakopmund.",
 "gecko-palmato": "Translúcido, con **membranas entre los dedos** que le hacen de raqueta sobre la arena y unos ojos enormes de nocturno. No tiene párpados: se limpia los ojos con la lengua.",
 "agama-namibia": "El macho no se puede pasar por alto: **cabeza y cuello naranja encendido** sobre cuerpo azul violáceo. Toma el sol en lo alto de los peñascos de granito.",
 "varano-roca": "Lagarto grande y robusto, de lengua bífida, que se ve cruzando pistas o rondando las charcas. Inofensivo si no lo arrinconas.",
 "tortuga-leopardo": "La tortuga terrestre grande del sur de África, con el caparazón moteado como un felino. **Cruza las carreteras muy despacio**: es de lo que más se atropella, así que ojo al asfalto.",
 "lagarto-pala": "El lagarto de la **ladera de deslizamiento** de la duna. El hocico en forma de pala le sirve para **«nadar» dentro de la arena**, y hace el baile térmico: levanta las patas por parejas para no quemarse. *(El que veas abajo, entre las matas, es su primo de nariz de cuña — ficha siguiente.)*",
 # --- COSTA, ROCA Y ARENA ---
 "lobo-marino": "En **Cape Cross** hay una de las mayores colonias del mundo: decenas de miles a la vista y oyéndose desde lejos. Aviso serio: **el olor es parte de la visita** — llevad pañuelo.",
 "delfin-heaviside": "Pequeño y rechoncho, con el dorso oscuro en forma de cono. **Endémico de la corriente de Benguela**: no vive en ninguna otra parte del mundo. Salta girando sobre sí mismo.",
 "daman": "Parece un roedor gordo, pero su pariente vivo más cercano es **el elefante**. En colonias sobre los roquedos, tomando el sol a primera hora.",
 "ardilla-terrestre": "En el suelo, con la **cola en abanico sobre el lomo haciendo de sombrilla**. Vive en colonias junto a sus madrigueras y es de lo más visible en las llanuras de Etosha.",
 "escarabajo-niebla": "El bicho que **bebe niebla**: sube a lo alto de la duna de madrugada y **hace el pino** para que la humedad condense en su caparazón y le resbale hasta la boca.",
 "escorpion": "Grande y negro, con la **cola gruesa**. Regla de oro: cola gruesa y pinzas finas = veneno potente; pinzas grandes y cola fina = poco peligro. **Sacude las botas cada mañana** y no dejes ropa en el suelo.",
 "arana-rueda": "Araña blanca y grande de las dunas, cazadora nocturna. El macho recorre cientos de metros por la noche buscando hembra y **«tamborilea» en la arena** para comunicarse — de ahí lo de *dancing white lady*.",
 # --- AVE anadida ---
 "pelicano": "Enorme y blanco, con el pico de bolsa amarillenta. Pesca en grupo en la laguna de **Walvis Bay**, y en el muelle se posan a un metro de la gente.",

 # --- BICHOS ---
 "termita": "No la verás a ella: verás **su edificio**. Los termiteros de metros de alto salpican toda la ruta, orientados para ventilarse solos. Son también las sospechosas del misterio de los **círculos de hadas** *(están en el cuaderno de joyas ocultas)*.",
 "escarabajo-pelotero": "Modela una bola de estiércol más grande que él y la empuja **de espaldas y en línea recta**. Esta especie se orienta de noche **por la Vía Láctea** — se le comprobó tapándole la vista del cielo.",
 "solifugo": "Ni araña ni escorpión: parece las dos cosas y **no es venenoso**. Corre como una bala hacia tu linterna —no hacia ti— y por eso asusta tanto en el campamento. Muerde si lo agarras: no lo agarres.",
 "gusano-mopane": "La oruga a rayas que devora los mopanes… y que en el norte se come **frita con tomate y chili**: es proteína seria y la venden en los mercados *(ver el manual de intendencia)*.",
 "shongololo": "Milpiés negro y brillante del grosor de un dedo. **Inofensivo**: se enrosca en espiral si lo tocas. Aparece a montones tras las primeras lluvias.",
 "anofeles": "Se posa con **el cuerpo inclinado**, en ángulo con la piel, y pica de noche. Sin dramatismo: **es el animal más peligroso del viaje** — Etosha es zona de malaria *(profilaxis, en la guía de preparación)*. Repelente al anochecer y manga larga.",

 # --- MAMIFEROS anadidos ---
 "zorro-orejudo": "Orejas descomunales que usa de radar para **oír insectos bajo tierra**. En pareja o en grupillo familiar, trotando por la llanura al amanecer y al atardecer.",
 "jineta": "Cuerpo alargado de gato, pelaje moteado y **cola anillada larguísima**. Nocturna y trepadora: la típica sombra que cruza el foco del campamento cuando cenáis.",
 "puercoespin": "El roedor grande de África, cubierto de **púas blancas y negras**. Nocturno; a menudo se ven solo las púas que va perdiendo por el camino.",
 "liebre-saltadora": "Ni liebre ni canguro, pero lo parece: **salta a dos patas** y sus ojos devuelven un reflejo rojo intenso a la linterna. Los guías la enseñan casi cada nocturno — aunque GBIF ni la registre: nada nocturno se sube.",
 "klipspringer": "Antilopito de los roquedos: se sostiene **de puntillas, sobre las pezuñas**, en piedras imposibles. Casi siempre en pareja y quieto, mirándote desde arriba. Damaraland y Twyfelfontein.",
 "mangosta-amarilla": "Rojiza-amarillenta, con la **punta de la cola blanca** y aire de zorrillo. De día y pegada a sus madrigueras. De las tres mangostas diurnas de la guía, es la de la cola blanca: la esbelta la lleva negra, y la rayada va en tropa.",
 "babuino-chacma": "El primate grande de los miradores y las áreas de descanso: hocico de perro, tropa jerárquica y cola quebrada en «L». En esta ruta vive en la escarpa y el roquedo; en Etosha apenas figura (9 registros GBIF). **Nada comestible a la vista**: donde hay turistas es un ladrón profesional.",
 "ballena-jorobada": "Aletas pectorales enormes y casi blancas —un tercio del cuerpo— y el salto más famoso del océano. **Migra frente a esta costa de junio a noviembre**: el crucero de Walvis Bay cae en temporada.",
 "mangosta-rayada": "La mangosta social: tropas de decenas, rayas transversales en el lomo y parloteo constante. Diurna y descarada — la contraria exacta de la amarilla, que va sola.",
 "zorro-del-cabo": "El único zorro verdadero del sur de África: pequeño, gris plata, con la cola tupida de punta negra. Estrictamente nocturno: es objetivo del safari nocturno, no del día.",
 "gato-montes-africano": "Como un atigrado espigado de patas largas, con el dorso de las orejas rojizo — esa es la seña frente al gato doméstico. Nocturno y discretísimo: verlo es premio.",
 "lobo-de-tierra": "Parece una hiena en miniatura, con crin eréctil y franjas verticales, pero cena termitas. Nocturno estricto: su cifra de GBIF infrarrepresenta, como la de la liebre saltadora.",
 # --- AVES anadidas ---
 "bateleur": "En vuelo **no se le ve cola**: es una tabla negra con la cabeza roja, y se balancea de lado a lado planeando. De los rapaces más reconocibles del parque.",
 "buitre-orejudo": "El buitre grande y feo, de **cabeza rosada desnuda** y pico enorme: es el que abre la piel del cadáver y deja comer al resto. Manda en la carroña.",
 "gaviota-hartlaub": "La gaviota del Benguela, endémica de esta costa y la sudafricana: pequeña, de capucha apenas grisácea y pico rojo oscuro. La nube blanca detrás de los barcos del muelle.",
 "avoceta": "Inconfundible: blanca y negra, con el pico finísimo curvado **hacia arriba**, barriendo el agua somera de lado a lado. En la laguna, repartida entre los flamencos.",
 "flamenco-comun": "**Más grande y más pálido** que el enano, con el pico rosa de punta negra —el del enano se ve oscuro entero—. Los dos comparten la laguna de Walvis Bay.",
 "cormoran-cabo": "Azulado oscuro con la cara amarilla. Vuela en **cintas larguísimas a ras del agua** frente a la costa; en Walvis Bay hay plataformas construidas para su guano.",
 "charran-damara": "Charrán pequeño con **gorra negra completa** y pico negro. Cría casi solo en la costa namibia y es **especie amenazada**: si veis un nido en la grava de la costa, ni acercarse.",
 "ostrero-africano": "Negro entero con **pico y patas rojo intenso**. De la costa rocosa; no llega a diez mil individuos en el mundo entero.",
 "francolin-picorrojo": "El «pollo» ruidoso de los campamentos: pardo con **pico y patas rojos**. Os despertará al amanecer, sin falta.",

 # --- Ampliacion del 10/08: el primer barrido COMPLETO de GBIF contra el catalogo ---
 "ardilla-matorral": "Parda grisácea, de vientre claro y cola larga poco tupida. Es la ardilla **de los árboles** —anida en los huecos del mopane, de ahí su apodo de «ardilla de los mopanes»— frente a la terrestre de cola en abanico, que es de las llanuras.",
 "mangosta-esbelta": "La solitaria de **punta de cola negra**, que levanta al correr. Baja, alargada y rojiza: cruza la pista como una flecha y se para en alto —un termitero, una rama— a mirar. La amarilla lleva la punta blanca; la rayada va en tropa.",
 "aguila-rapaz": "Parda entera, del canela claro al chocolate —cada individuo de un tono—, sin el pecho blanco del águila marcial. Posada **a la vista en lo alto de una acacia o un poste**, y baja a las carroñas junto a la pista: es la gran águila más registrada del parque.",
 "avefria-armada": "De esmoquin: blanco, negro y gris, con el **ojo rojo intenso**. Su reclamo metálico de alarma —«tink, tink», el martillo del herrero en el yunque— le da el nombre inglés de *blacksmith*. Se oye antes de verse.",
 "drongo": "Negro entero de reflejos azulados, **ojo rojo** y cola ahorquillada de golondrina. Caza al vuelo lo que levantan los herbívoros — y los coches. En el Kalahari se le ha medido robando comida **imitando las llamadas de alarma** de otras especies.",
 "pintada": "Inconfundible: cuerpo pizarra sembrado de **puntos blancos**, cabeza desnuda azulada y **casco córneo**. Bandadas desordenadas por los arcenes, corriendo antes que volando.",
 "quelea": "Del tamaño de un gorrión, pardo, con **pico rojo** y antifaz negro en los machos. La gracia no es el individuo: es **el enjambre** — miles bebiendo y girando a la vez como un banco de peces. Considerada el ave silvestre más abundante del mundo.",
 "turaco-unicolor": "Gris entero, con **cresta despeinada** y cola larga. Se presenta él solo: su reclamo nasal y quejumbroso —«g'waaay»— le vale el nombre inglés de *go-away bird*.",
 "toco-piquinegro": "El tercer cálao del eje: **gris ceniza** donde los otros dos visten blanco y negro, con ceja clara. El pico delata el sexo — oscuro con una cuña clara el macho, **marfil con la punta rojiza** la hembra (la de la foto).",
 "bulbul-encapuchado": "Capucha negruzca, pecho pardo claro, amarillo bajo la cola — y un **anillo ocular naranja-rojo** carnoso que se ve de lejos y lo distingue de cualquier otro pájaro de campamento.",
 "turdoide-caricalvo": "**Casi endémico de Namibia**: claro por abajo, alas pardas, corona blanca y la **mejilla desnuda y negra** que le da nombre. En cuadrillas ruidosas que rebuscan por el suelo — y hay quien lo ve atacar su reflejo en los retrovisores.",
 # --- REPTILES anadidos el 10/08 ---
 "escinco-arboricola": "El lagarto diurno de los campamentos: liso, brillante, con **rayas claras** a lo largo del cuerpo moteado. Corretea por troncos, muretes y suelos a plena luz. En el Kalahari es famoso por instalarse en los nidos del tejedor republicano.",
 "gecko-fischer": "Nocturno, de **ojos grandes anaranjados** y piel granujienta con bandas pardas. De día, en grietas; de noche sale a la vista sobre rocas y muros a cazar insectos. Inofensivo — déjalo trabajar.",
 "galapago-africano": "La tortuga **de agua** de las charcas: caparazón pardo aplanado y cabeza moteada que asoma como un periscopio. Toma el sol en el borde, y en Etosha está documentada cazando en grupo **quéleas** que bajan a beber — arrastrándolas al fondo.",

 # --- Ampliacion del 11/08: el barrido completo de las otras tres zonas ---
 "delfin-mular": "El delfín grande y gris de aleta curvada — 3 metros frente al 1,7 del Heaviside, que la lleva triangular. En la bahía **se reparten el agua por profundidades**: el mular pega a la costa, el Heaviside más afuera.",
 "rata-dassie": "Parece una ardilla a la que la cola no le llegó a plumero — y es **la única especie viva de toda su familia**. Diurna, tomando el sol en las peñas; el cráneo aplanado y las costillas flexibles le dejan **colarse por grietas imposibles**.",
 "charran-comun": "Esbelto y pálido, de vuelo elástico, con **gorra negra incompleta y frente blanca** en estas fechas *(es su plumaje de invierno)*. No cría aquí: **viene de Europa a pasar el verano austral**, y viene en masa.",
 "gaviota-cocinera": "La gaviota **grande, de dorso y alas negras** y pico amarillo con punto rojo. La otra del muelle —pequeña, pálida, de pico oscuro— es la de Hartlaub: verlas juntas es la comparación hecha.",
 "estornino-naburup": "Negro brillante con el **ojo naranja encendido** y una **ventana clara en el ala** que estalla al volar. Confiado hasta el descaro donde hay gente: merodea picnics y parrillas.",
 "sison-damara": "Sisón pálido del desierto, con **línea negra bajando por el cuello** en el macho. Casi endémico de Namibia y el suroeste de Angola. Anda por la grava **en parejas**, con paso lento — y grita al amanecer.",
 "avutarda-namibia": "Avutarda grande de **nuca parda y cuello gris**, caminando despacio por las llanuras de grava. **En Peligro**: su gran amenaza son los tendidos eléctricos, con los que choca en vuelo.",
 "alondra-dunas": "Alondra rojiza como su duna, de pecho apenas rayado, correteando entre las matas de hierba de la arena. Sin marcas llamativas — la gracia es otra: **casi toda su especie vive dentro de Namibia**.",
 "lorito-ruppell": "Loro pequeño y **gris oscuro** con los hombros amarillos y el ojo rojo — y el dimorfismo al revés: **la del vientre y trasero azules es la hembra**. Se delata por el chillido en los cauces arbolados.",
 "toco-angoleno": "Toco de **pico rojo largo**, cabeza oscura, vientre blanco y alas sembradas de gotas blancas. Casi endémico, y **el único de su familia que come solo insectos**: por eso puede vivir donde no hay fruta.",
 "inseparable-namibia": "Loro diminuto **verde con la cara rosa**, en bandadas chillonas por los roquedos. Casi endémico. Anida donde nadie: **dentro de los pajares del tejedor republicano** — el inquilino de la ficha del tejedor.",
 # --- REPTILES anadidos el 11/08 ---
 "gecko-diurno": "La rareza: un **gecko que cambió la noche por el día** —la diurnidad evolucionó en su género— y corre por las rocas de la costa de la niebla. Pálido, de ojos grandes, siempre al sol.",
 "lagarto-cuna": "El lagarto que de verdad te cruzas en Sossusvlei: vive **abajo, en la base vegetada de la duna** —donde caminas tú—, esprintando de mata en mata, gris arena con motas claras y flancos punteados. El hocico acaba en cuña, no en pala.",

 # --- Ampliacion del 15/08: los felinos y las rapaces, todos y aparte (es lo que mas interesa) ---
 "caracal": "Felino de talla media, **rojizo uniforme y sin manchas**, con **pinceles negros en las orejas** y cara de lince. Solitario y sobre todo nocturno; de día, como mucho, cruzando una pista a primera hora. Es el que salta a por aves al vuelo.",
 "gato-patas-negras": "El felino **más pequeño de África** —menos que un gato doméstico—, moteado y con **bandas negras en las patas**; las plantas de los pies, negras, le dan nombre. Estrictamente nocturno y casi imposible de ver: si en el nocturno veis un «gato» pequeño y muy manchado, es este — el gato montés es más grande, casi liso y con el dorso de las orejas rojizo.",
 "aguila-cafre": "Águila grande y **negra entera** con una **V blanca en la espalda** y obispillo blanco; en vuelo, alas estrechas en la base y anchas en la mano, en forma de **hoja**. Águila **de acantilado**: la de la escarpa, los pasos y los roquedos —come damanes—, no la de la llanura.",
 "aguila-azor-africana": "Águila mediana, **negra por arriba y blanca con estrías negras por abajo**, patas emplumadas; en pareja, en el monte arbolado, cazando pintadas y francolines. Los jóvenes son rojizos por abajo, sin nada de blanco: otra ave, a efectos prácticos.",
 "aguila-wahlberg": "Águila mediana, **parda uniforme** con una **cresta corta** que apunta hacia atrás y **cola larga y estrecha**; en vuelo, alas y cola rectas como una cruz. Migrante intraafricana que **llega en agosto-septiembre a criar**: está en vuestras fechas. Hay una forma pálida.",
 "aguila-calzada": "**La misma que cría en España**: pequeña, patas emplumadas, forma clara (cuerpo blanco y alas oscuras, con las «luces» blancas en los hombros) y forma oscura. Aquí es a la vez invernante europea y residente del sur; en el Namib, la de la escarpa.",
 "aguila-pomerana": "Águila mediana, parda con la **cabeza y las cubiertas más claras** que las alas —el «águila con chaleco»—; en vuelo, alas anchas y una **mancha blanca en forma de coma** en la base de las primarias por arriba. Migrante del este de Europa que llega en noviembre; muy escasa aquí.",
 "culebrera-pechinegra": "Águila mediana con **capucha y pecho negros y vientre blanco puro**, **ojo amarillo** grande de culebrera y cabeza redonda; en vuelo, alas blancas por debajo. **Se cierne** —una de las pocas águilas que lo hace— sobre las llanuras y se posa en lo alto de árboles y postes.",
 "culebrera-sombria": "Parda oscura entera, con **cabeza grande y redonda de ojos amarillos** enormes y **patas desnudas** grises; en vuelo, las plumas de vuelo blancas contra el cuerpo oscuro. Muy quieta en lo alto de un árbol seco, mirando al suelo horas.",
 "aguila-pescadora": "**El águila de las playas del mundo entero**: blanca por abajo, parda por arriba, con **antifaz negro** en la cabeza blanca; se cierne sobre el agua y **se zambulle de pies** a por el pez. Invernante europea en la laguna de Walvis Bay.",
 "buitre-cabeciblanco": "Buitre grande de **cabeza blanca y desnuda con la cara rosada**, pico anaranjado de punta azulada, y **vientre y «calzones» blancos** que en vuelo contrastan con las alas negras. Casi siempre solo o en pareja, no en la piña de los dorsiblancos; suele llegar el primero a la carroña.",
 "gavilan-gabar": "Gavilán pequeño, gris con el **pecho blanco finamente barrado**, **cera y patas rojas** y **obispillo blanco** al volar; hay una forma negra (melánica) casi entera. Se posa dentro de la copa, no en lo alto como el azor lagartijero, y caza pajarillos en los recintos.",
 "gavilan-chikra": "Gavilán pequeño y pálido: gris por arriba, **finamente barrado de rojizo** por abajo, **ojo rojo** en el macho y patas amarillas. En el monte y los recintos, con vuelo rápido y directo. Allí es el *little banded goshawk*.",
 "aguilucho-caricalvo": "Rapaz gris de **cara desnuda amarilla** que se pone roja al excitarse, cola negra con banda blanca y **patas de doble articulación**: mete la pata en huecos y nidos de tejedor a por pollos y trepa por los troncos como un pájaro carpintero torpe.",
 "aguilucho-papialbo": "Aguilucho de llanura, **vuelo bajo y bamboleante** con las alas en V; el macho gris muy pálido con la punta del ala negra en cuña. Invernante europeo: llega en octubre-noviembre a las llanuras del este de Etosha. Hembras y jóvenes, pardos con obispillo blanco — casi imposibles de separar del cenizo en el campo.",
 "aguilucho-cenizo": "El otro aguilucho europeo del verano austral: macho gris con **una banda negra en el ala** por arriba y **rayas rojizas** en el vientre; hembras y jóvenes pardos con obispillo blanco. Vuela bajo, a ras de la hierba, ladeándose. En Etosha, de noviembre en adelante.",
 "elanio": "Blanco y gris pálido con los **hombros negros** y el **ojo rojo**; **se cierne** como un cernícalo sobre la hierba y se posa en postes y cables junto a la carretera. Allí lo llaman *black-shouldered kite*.",
 "milano-negro": "Pardo oscuro con **cola ahorquillada** que gira como un timón; vuelo flotante, alas anguladas. Casi todos los de aquí son de **pico amarillo** —el milano piquigualdo, que la mayoría trata como raza suya (*M. aegyptius parasitus*) y GBIF cuenta aparte con menos registros—. Llegan con las lluvias: en Etosha los registros arrancan en noviembre y se disparan de diciembre a febrero. Ronda basureros, campamentos y carreteras.",
 "busardo-ratonero": "El ratonero de Europa en su raza oriental (*vulpinus*), **rojiza y con la cola canela**: pasa aquí el verano austral y llega en octubre-noviembre. Posado en postes junto a la carretera; el ratonero típico, sin nada llamativo — lo que lo distingue es la fecha.",
 "busardo-augur": "Compacto y contrastado: **negro por arriba, blanco por abajo, cola rojo ladrillo** corta y ancha. Planea con las alas en V y se cierne sobre la escarpa; hay una forma oscura. Es la rapaz de la roca en Damaraland.",
 "busardo-augur-meridional": "El primo del sur: negro por arriba, **pecho rojo ladrillo** y la misma cola roja. Su reclamo, un ladrido de chacal que le da el nombre inglés. Escarpa y montaña: Spreetshoogte, Naukluft.",
 "cernicalo-ojiblanco": "El cernícalo grande de Etosha: canela con **barras negras finas** por todas partes, sin bigotera, y el **ojo pálido, casi blanco** — de ahí el nombre. Posado en postes y acacias de la llanura; se cierne poco. **El halcón más registrado del parque.**",
 "cernicalo-africano": "El cernícalo vulgar de aquí: **cabeza y cola grises** en los dos sexos, dorso rojizo moteado, bigotera fina, y se **cierne** contra el viento sobre roquedos y dunas. Cañón de Sesriem, escarpa y costa. Lo que en España es cernícalo, aquí es este.",
 "alcotan-turumti": "Halcón pequeño y muy elegante: **capucha rojiza (cabeza y nuca canela)**, cuerpo gris finamente barrado y bigotera negra. Caza pajarillos en vuelo bajo y rapidísimo, en pareja; **ligado a las palmeras**.",
 "halcon-borni": "Halcón grande de **corona rojiza** y bigotera fina, gris por arriba y crema apenas manchado por abajo; alas más anchas y vuelo menos brusco que el peregrino. Caza en las charcas cuando bajan a beber las gangas y las palomas — buscadlo posado cerca del agua.",
 "halcon-peregrino": "El más rápido: compacto, **capucha y bigotera negras anchas**, gris pizarra por arriba y **densamente barrado** por abajo, alas puntiagudas. La raza africana (*minor*) es pequeña y oscura. Costa y acantilados; en Etosha, sobre todo la europea de paso.",
 "halconcito-africano": "**La rapaz más pequeña de África** —del tamaño de un alcaudón—: blanca por abajo, gris por arriba, la hembra con la **espalda castaña**, patas y cera rojas. Vive **dentro de los pajares del tejedor republicano**: se le busca posado encima de uno, bombeando la cola.",
 "buho-manchado": "El búho mediano de **orejas** y **ojos amarillos**, gris moteado; en muros, postes y suelo de los campamentos al anochecer, y en el asfalto de noche a por insectos. El otro búho grande con orejas, el lácteo, tiene los ojos oscuros y es mucho mayor.",
 "autillo-africano": "Diminuto y **gris corteza**, con orejas, ojos amarillos y un camuflaje que lo convierte en un trozo de rama pegado al tronco. Se delata de noche por su **«prrrp» monótono** cada pocos segundos, como un grillo. Los recintos de los campamentos.",
 "autillo-cariblanco": "Pequeño, gris muy claro con **cara blanca enmarcada en negro** y **ojos naranja** intenso; orejas grandes. Estira el cuerpo y entrecierra los ojos para volverse rama cuando lo miran. Campamentos y monte de acacias.",
 "mochuelo-perlado": "Un puño de plumas, **diurno**, con «perlas» blancas en el dorso y **dos falsos ojos negros en la nuca**. Se posa a la vista de día y silba una escala ascendente que todos los pajarillos vienen a increpar — seguid el escándalo y lo encontráis.",
 "lechuza-comun": "La misma que en casa: **cara blanca en forma de corazón**, ojos negros, dorada por arriba y pálida por abajo. De noche en los recintos y al borde de la luz de las charcas iluminadas; a veces dentro de un pajar de tejedor.",
 "buho-moro": "Búho de las **llanuras herbosas**, pardo oscuro con disco facial pálido y ojos oscuros; **caza al atardecer, volando bajo como un aguilucho** sobre la hierba, y se levanta de la cuneta al pasar el coche; de noche ronda la luz de las charcas iluminadas.",
}
