# Texto de identificacion por especie (rasgos morfologicos, no cifras sin fuente).
# La linea "donde y cuando en Etosha" se rellena aparte, con fuente.

ID = {
 # --- MAMIFEROS ---
 "elefante": "El mayor animal terrestre. Orejas enormes con forma de África y dos «dedos» en la punta de la trompa. Los de Etosha se ven blanquecinos: se rebozan en el polvo calcáreo del pan.",
 "rino-negro": "El labio superior es **puntiagudo y prensil** —ramonea arbustos—, la cabeza va alta y lleva dos cuernos. Solitario y de genio corto. Se distingue del blanco por el labio, nunca por el color.",
 "rino-blanco": "Labio **ancho y cuadrado** para pacer hierba, cabeza baja y joroba en la nuca. Más grande y más sociable que el negro. Lo de «blanco» viene de *wijd* (ancho) en afrikáans.",
 "leon": "Melena en el macho, pardo uniforme. Con calor pasa el día tumbado a la sombra: la actividad es al alba, al anochecer y de noche.",
 "leopardo": "Rosetas **sin punto central**, cuerpo bajo y macizo, cola larguísima. Nocturno y arborícola: el más difícil de ver de los grandes.",
 "guepardo": "Manchas **simples**, no rosetas, y dos «lágrimas» negras del ojo a la boca. Silueta esbelta de galgo con cabeza pequeña. Caza de día, a plena luz.",
 "jirafa": "La subespecie del suroeste, de manchas irregulares que se desvanecen hacia las patas. Al beber tiene que abrir las patas en compás: su momento más vulnerable, y el mejor para la foto.",
 "cebra-burchell": "La cebra de llanura: rayas **anchas** que siguen hasta la barriga, con «rayas de sombra» pardas intercaladas. Es la que forma manadas en las charcas.",
 "cebra-hartmann": "Rayas **finas y apretadas**, barriga blanca sin rayar, papada colgante y una «parrilla» de rayas horizontales en la grupa. De terreno rocoso y escarpado.",
 "orix": "Cuernos rectos como lanzas —en el macho y en la hembra— y máscara facial en blanco y negro. Aguanta sin beber; es el emblema del país y sale en el escudo de Namibia.",
 "springbok": "Banda castaña que separa el lomo del vientre blanco, y una cresta de pelo blanco en la grupa que abre al saltar. Da botes rígidos con el lomo arqueado: el *pronking*.",
 "kudu": "El macho lleva cuernos en espiral y una uve blanca entre los ojos; el costado, rayas verticales finas. **Salta vallas altísimas: es el gran peligro de la carretera al anochecer.**",
 "eland": "El antílope más grande y pesado, de aspecto casi bovino: papada colgante y cuernos rectos con una espiral en la base.",
 "nu": "Morro cuadrado, crin y barba oscuras, cuernos que bajan y vuelven a subir. Silueta desconcertante: toro por delante, caballo por detrás.",
 "impala-cara-negra": "**Subespecie endémica** del noroeste de Namibia y el suroeste de Angola: como la impala común, pero con una franja negra bien marcada en la cara. Escasa y protegida.",
 "dikdik": "Antílope diminuto, a la altura de la rodilla, con trompita móvil y un penacho de pelo en la frente. Casi siempre en pareja y pegado al monte espeso.",
 "hiena-manchada": "Pelaje moteado, cuello grueso, **orejas redondas** y lomo caído hacia atrás. Es la que se oye de noche desde la tienda.",
 "hiena-parda": "Melena larga y desgreñada de pelo oscuro y **orejas puntiagudas**. Mucho más rara y esquiva que la manchada; verla es un premio.",
 "chacal": "La «silla de montar» negra y plateada sobre el lomo, y orejas grandes. Omnipresente en las charcas y desvergonzado en los campamentos.",
 "ratel": "Manto gris claro desde la cabeza hasta la cola sobre cuerpo negro. Pequeño, bajo, y con una fama de temerario que se ha ganado a pulso.",
 "facocero": "Verrugas en la cara y colmillos curvos hacia arriba. Corre con la cola tiesa como una antena y **se arrodilla sobre los codos** para pacer.",
 "suricata": "De pie, haciendo de centinela sobre un montículo. ⚠️ **Ojo: NO es de Etosha** — vive en el Kalahari y el sur del país, así que en esta ruta no toca. Va aquí porque todo el mundo la busca.",
 "hartebeest": "Cara larguísima y estrecha, cuernos en forma de arpa montados sobre un pedúnculo, y grupa muy caída. Color rojizo brillante al sol.",
 "steenbok": "Pequeño, rojizo y con orejas enormes; solo el macho lleva cuernos, cortos y rectos. Se queda clavado mirándote y sale disparado en zigzag.",
 # --- AVES ---
 "avestruz": "El ave más grande del mundo. El macho, negro y blanco; la hembra, parda. En Etosha se ven cruzando la llanura abierta.",
 "avutarda-kori": "Una de las aves voladoras más pesadas que existen. Camina por la llanura con paso solemne; en exhibición el macho hincha el cuello como un globo blanco.",
 "secretario": "Rapaz de patas larguísimas que **caza andando** y mata serpientes a pisotones. Las plumas negras de la nuca le dan el nombre, como plumas de escribiente tras la oreja.",
 "carraca-lila": "La postal de África: pecho lila, garganta azul y alas turquesa que estallan al volar. Se posa a la vista, en un poste o una rama seca.",
 "calao-amarillo": "Pico grande, curvo y **amarillo**. Confiado y muy presente en los campamentos, donde vigila las mesas del desayuno.",
 "calao-rojo": "Idéntico en forma al anterior, pero con el pico **rojo**. Los dos conviven en la misma zona: mira el pico y ya está.",
 "tejedor-republicano": "Se ve **el nido antes que el pájaro**: pajares colectivos gigantes que engullen un árbol o un poste de la luz y que ocupan generaciones enteras.",
 "aguila-marcial": "La mayor águila de África: capucha oscura y pecho blanco moteado. Suele estar posada, inmóvil, en lo alto de una acacia.",
 "buitre-dorsiblanco": "El buitre común de la sabana. El dorso pálido que le da nombre solo se le ve bien en vuelo.",
 "flamenco-enano": "Más pequeño y más intensamente rosa que el común, con el pico oscuro de lejos. **Depende por completo de que haya agua en el pan.**",
 "grulla-azul": "Gris azulada, con la cabeza abultada y unas largas plumas alares que arrastra como una cola. Elegantísima y, aquí, rareza.",
 "ganga-namaqua": "Cola muy puntiaguda; llega a las charcas en bandos y a horas fijas. El macho **empapa las plumas del vientre** para llevarles agua a los pollos.",
 "sison-negro": "El macho es negro con grandes parches blancos en el ala; se delata con un chillido metálico al levantar el vuelo.",
 "azor-lagartijero": "Gris claro, con patas y cera del pico **rojas**. Casi siempre posado en un poste, oteando el suelo.",
 "alcaudon-carmesi": "Negro por arriba y **rojo intenso** por abajo: imposible de confundir. Se mueve por dentro del matorral espeso.",
 "buho-lacteo": "El búho más grande de África, con **párpados rosados** que se le ven al parpadear. En los árboles grandes de los campamentos.",
 "abejaruco-carmin": "Carmesí con la cabeza azul turquesa. Es **migrador de verano austral**: llega al norte del país justo por estas fechas.",
 "ciguena-abdim": "Cigüeña pequeña y oscura, de patas grises con las «rodillas» rojas. Llega con las primeras lluvias y por eso la llaman la cigüeña de la lluvia.",
 "estornino-cabo": "Azul verdoso metálico con el ojo naranja. En los campamentos, siempre atento a las migas de la mesa.",
 "pigargo-vocinglero": "Cabeza blanca y pecho castaño; su reclamo es, literalmente, el sonido de África. Necesita agua abierta, así que aquí depende del pan y de las charcas grandes.",

 # --- REPTILES ---
 "vibora-bufadora": "Gruesa, corta y con galones en uve por el lomo. **No huye: se queda quieta confiando en su camuflaje**, y de ahí que se le atribuyan la mayoría de mordeduras graves del continente. Mira dónde pisas al anochecer y nada de andar descalzo por el campamento.",
 "cobra-cebra": "Del suroeste africano, con bandas oscuras. **Escupe el veneno a los ojos** a varios metros y con puntería. Si levanta el cuerpo y abre la capucha, retrocede despacio: nunca la acorrales.",
 "mamba-negra": "Larga, delgada y **gris oliva** —lo negro es el interior de la boca, no la piel—. Rapidísima y nerviosa, pero esquiva: lo normal es no verla. La peor fama de África, y en buena parte merecida.",
 "vibora-peringuey": "Diminuta, de la arena del Namib. **Se entierra dejando fuera solo los ojos** y se desplaza de lado. Suya es la huella en zigzag que aparece en las dunas por la mañana.",
 "vibora-cornuda": "Un «cuerno» escamoso sobre cada ojo. Se entierra en la arena o la grava del desierto y espera. Pequeña, pero con veneno de verdad.",
 "camaleon-namib": "El camaleón que **corre por el suelo del desierto** en vez de trepar. Cambia de color para regular su temperatura: oscuro de mañana para calentarse, pálido al mediodía. La estrella de los tours de «desierto vivo» de Swakopmund.",
 "gecko-palmato": "Translúcido, con **membranas entre los dedos** que le hacen de raqueta sobre la arena y unos ojos enormes de nocturno. No tiene párpados: se limpia los ojos con la lengua.",
 "agama-namibia": "El macho no se puede pasar por alto: **cabeza y cuello naranja encendido** sobre cuerpo azul violáceo. Toma el sol en lo alto de los peñascos de granito.",
 "varano-roca": "Lagarto grande y robusto, de lengua bífida, que se ve cruzando pistas o rondando las charcas. Inofensivo si no lo arrinconas.",
 "tortuga-leopardo": "La tortuga terrestre grande del sur de África, con el caparazón moteado como un felino. **Cruza las carreteras muy despacio**: es de lo que más se atropella, así que ojo al asfalto.",
 "lagarto-pala": "El lagarto de las dunas. El hocico en forma de pala le sirve para **«nadar» dentro de la arena**, y hace el baile térmico: levanta las patas por parejas para no quemarse.",
 # --- COSTA, ROCA Y ARENA ---
 "lobo-marino": "En **Cape Cross** hay una de las mayores colonias del mundo: decenas de miles a la vista y oyéndose desde lejos. Aviso serio: **el olor es parte de la visita** — llevad pañuelo.",
 "delfin-heaviside": "Pequeño y rechoncho, con el dorso oscuro en forma de cono. **Endémico de la corriente de Benguela**: no vive en ninguna otra parte del mundo. Salta girando sobre sí mismo.",
 "daman": "Parece un roedor gordo, pero su pariente vivo más cercano es **el elefante**. En colonias sobre los roquedos, tomando el sol a primera hora.",
 "ardilla-terrestre": "En el suelo, con la **cola en abanico sobre el lomo haciendo de sombrilla**. Vive en colonias junto a sus madrigueras y es de lo más visible en las llanuras de Etosha.",
 "escarabajo-niebla": "El bicho que **bebe niebla**: sube a lo alto de la duna de madrugada y **hace el pino** para que la humedad condense en su caparazón y le resbale hasta la boca.",
 "escorpion": "Grande y negro, con la **cola gruesa**. Regla de oro: cola gruesa y pinzas finas = veneno potente; pinzas grandes y cola fina = poco peligro. **Sacude las botas cada mañana** y no dejes ropa en el suelo.",
 "arana-rueda": "Araña blanca y grande de las dunas, cazadora nocturna. El macho recorre cientos de metros por la noche buscando hembra y **«tamborilea» en la arena** para comunicarse — de ahí lo de *dancing white lady*.",
 # --- AVE anadida ---
 "pelicano": "Enorme y blanco, con el pico de bolsa amarillenta. Pesca en grupo en la laguna de **Walvis Bay**, y en el muelle se posan a un metro de la gente.",

 # --- BICHOS ---
 "termita": "No la verás a ella: verás **su edificio**. Los termiteros de metros de alto salpican toda la ruta, orientados para ventilarse solos. Son también las sospechosas del misterio de los **círculos de hadas** *(están en el cuaderno de joyas ocultas)*.",
 "escarabajo-pelotero": "Modela una bola de estiércol más grande que él y la empuja **de espaldas y en línea recta**. Esta especie se orienta de noche **por la Vía Láctea** — se le comprobó tapándole la vista del cielo.",
 "solifugo": "Ni araña ni escorpión: parece las dos cosas y **no es venenoso**. Corre como una bala hacia tu linterna —no hacia ti— y por eso asusta tanto en el campamento. Muerde si lo agarras: no lo agarres.",
 "gusano-mopane": "La oruga a rayas que devora los mopanes… y que en el norte se come **frita con tomate y chili**: es proteína seria y la venden en los mercados *(ver el manual de intendencia)*.",
 "shongololo": "Milpiés negro y brillante del grosor de un dedo. **Inofensivo**: se enrosca en espiral si lo tocas. Aparece a montones tras las primeras lluvias.",
 "anofeles": "Se posa con **el cuerpo inclinado**, en ángulo con la piel, y pica de noche. Sin dramatismo: **es el animal más peligroso del viaje** — Etosha es zona de malaria *(profilaxis, en la guía de preparación)*. Repelente al anochecer y manga larga.",

 # --- MAMIFEROS anadidos ---
 "zorro-orejudo": "Orejas descomunales que usa de radar para **oír insectos bajo tierra**. En pareja o en grupillo familiar, trotando por la llanura al amanecer y al atardecer.",
 "jineta": "Cuerpo alargado de gato, pelaje moteado y **cola anillada larguísima**. Nocturna y trepadora: la típica sombra que cruza el foco del campamento cuando cenáis.",
 "puercoespin": "El roedor grande de África, cubierto de **púas blancas y negras**. Nocturno; a menudo se ven solo las púas que va perdiendo por el camino.",
 "liebre-saltadora": "Ni liebre ni canguro, pero lo parece: **salta a dos patas** y sus ojos devuelven un reflejo rojo intenso a la linterna. Es de lo más visto en el safari nocturno.",
 "klipspringer": "Antilopito de los roquedos: se sostiene **de puntillas, sobre las pezuñas**, en piedras imposibles. Casi siempre en pareja y quieto, mirándote desde arriba. Damaraland y Twyfelfontein.",
 "mangosta-amarilla": "Rojiza-amarillenta, con la **punta de la cola blanca** y aire de zorrillo. Es la mangosta que de verdad se ve en Etosha, de día y junto a sus madrigueras.",
 "oricteropo": "El premio gordo del safari nocturno: orejas de burro, hocico de cerdo y cola de canguro. **Estrictamente nocturno y rarísimo de ver** — sus excavaciones en los termiteros sí se ven por todas partes.",
 # --- AVES anadidas ---
 "bateleur": "En vuelo **no se le ve cola**: es una tabla negra con la cabeza roja, y se balancea de lado a lado planeando. De los rapaces más reconocibles del parque.",
 "buitre-orejudo": "El buitre grande y feo, de **cabeza rosada desnuda** y pico enorme: es el que abre la piel del cadáver y deja comer al resto. Manda en la carroña.",
 "flamenco-comun": "**Más grande y más pálido** que el enano, y con el pico rosa con la punta negra —el del enano se ve oscuro entero—. Los dos comparten la laguna de Walvis Bay.",
 "cormoran-cabo": "Azulado oscuro con la cara amarilla. Vuela en **cintas larguísimas a ras del agua** frente a la costa; en Walvis Bay hay plataformas construidas para su guano.",
 "charran-damara": "Charrán pequeño con **gorra negra completa** y pico negro. Cría casi solo en la costa namibia y es **especie amenazada**: si veis un nido en la grava de la costa, ni acercarse.",
 "ostrero-africano": "Negro entero con **pico y patas rojo intenso**. De la costa rocosa; no llega a diez mil individuos en el mundo entero.",
 "francolin-picorrojo": "El «pollo» ruidoso de los campamentos: pardo con **pico y patas rojos**. Os despertará al amanecer, sin falta.",
}
