# Texto de identificacion por especie (rasgos morfologicos, no cifras sin fuente).
# La linea "donde y cuando en Etosha" se rellena aparte, con fuente.

ID = {
 # --- MAMIFEROS ---
 "elefante": "El mayor animal terrestre. Orejas enormes con forma de África y dos «dedos» en la punta de la trompa. Los de Etosha se ven blanquecinos: se rebozan en el polvo calcáreo del pan.",
 "rino-negro": "El labio superior es **puntiagudo y prensil** —ramonea arbustos—, la cabeza va alta y lleva dos cuernos. Solitario y de genio corto. Se distingue del blanco por el labio, nunca por el color.",
 "rino-blanco": "Labio **ancho y cuadrado** para pacer hierba, cabeza baja y joroba en la nuca. Más grande y más sociable que el negro. Lo de «blanco» viene de *wijd* (ancho) en afrikáans.",
 "leon": "Melena en el macho, pardo uniforme. Con calor pasa el día tumbado a la sombra: la actividad es al alba, al anochecer y de noche.",
 "leopardo": "Rosetas **sin punto central**, cuerpo bajo y macizo, cola larguísima. Nocturno y arborícola: el más difícil de ver de los grandes.",
 "guepardo": "Manchas **simples**, no rosetas, y dos «lágrimas» negras del ojo a la boca. Silueta esbelta de galgo con cabeza pequeña. Caza de día, a plena luz.",
 "jirafa": "La subespecie del suroeste, de manchas irregulares que se desvanecen hacia las patas. Al beber tiene que abrir las patas en compás: su momento más vulnerable, y el mejor para la foto.",
 "cebra-burchell": "La cebra de llanura: rayas **anchas** que siguen hasta la barriga, con «rayas de sombra» pardas intercaladas. Es la que forma manadas en las charcas.",
 "cebra-hartmann": "Rayas **finas y apretadas**, barriga blanca sin rayar, papada colgante y una «parrilla» de rayas horizontales en la grupa. De terreno rocoso y escarpado.",
 "orix": "Cuernos rectos como lanzas —en el macho y en la hembra— y máscara facial en blanco y negro. Aguanta sin beber; es el emblema del país y sale en el escudo de Namibia.",
 "springbok": "Banda castaña que separa el lomo del vientre blanco, y una cresta de pelo blanco en la grupa que abre al saltar. Da botes rígidos con el lomo arqueado: el *pronking*.",
 "kudu": "El macho lleva cuernos en espiral y una uve blanca entre los ojos; el costado, rayas verticales finas. **Salta vallas altísimas: es el gran peligro de la carretera al anochecer.**",
 "eland": "El antílope más grande y pesado, de aspecto casi bovino: papada colgante y cuernos rectos con una espiral en la base.",
 "nu": "Morro cuadrado, crin y barba oscuras, cuernos que bajan y vuelven a subir. Silueta desconcertante: toro por delante, caballo por detrás.",
 "impala-cara-negra": "**Subespecie endémica** del noroeste de Namibia y el suroeste de Angola: como la impala común, pero con una franja negra bien marcada en la cara. Escasa y protegida.",
 "dikdik": "Antílope diminuto, a la altura de la rodilla, con trompita móvil y un penacho de pelo en la frente. Casi siempre en pareja y pegado al monte espeso.",
 "hiena-manchada": "Pelaje moteado, cuello grueso, **orejas redondas** y lomo caído hacia atrás. Es la que se oye de noche desde la tienda.",
 "hiena-parda": "Melena larga y desgreñada de pelo oscuro y **orejas puntiagudas**. Mucho más rara y esquiva que la manchada; verla es un premio.",
 "chacal": "La «silla de montar» negra y plateada sobre el lomo, y orejas grandes. Omnipresente en las charcas y desvergonzado en los campamentos.",
 "ratel": "Manto gris claro desde la cabeza hasta la cola sobre cuerpo negro. Pequeño, bajo, y con una fama de temerario que se ha ganado a pulso.",
 "facocero": "Verrugas en la cara y colmillos curvos hacia arriba. Corre con la cola tiesa como una antena y **se arrodilla sobre los codos** para pacer.",
 "suricata": "Se la ve antes de pie, haciendo de centinela sobre un montículo, que caminando. Terreno abierto, seco y con vista.",
 "hartebeest": "Cara larguísima y estrecha, cuernos en forma de arpa montados sobre un pedúnculo, y grupa muy caída. Color rojizo brillante al sol.",
 "steenbok": "Pequeño, rojizo y con orejas enormes; solo el macho lleva cuernos, cortos y rectos. Se queda clavado mirándote y sale disparado en zigzag.",
 # --- AVES ---
 "avestruz": "El ave más grande del mundo. El macho, negro y blanco; la hembra, parda. En Etosha se ven cruzando la llanura abierta.",
 "avutarda-kori": "Una de las aves voladoras más pesadas que existen. Camina por la llanura con paso solemne; en exhibición el macho hincha el cuello como un globo blanco.",
 "secretario": "Rapaz de patas larguísimas que **caza andando** y mata serpientes a pisotones. Las plumas negras de la nuca le dan el nombre, como plumas de escribiente tras la oreja.",
 "carraca-lila": "La postal de África: pecho lila, garganta azul y alas turquesa que estallan al volar. Se posa a la vista, en un poste o una rama seca.",
 "calao-amarillo": "Pico grande, curvo y **amarillo**. Confiado y muy presente en los campamentos, donde vigila las mesas del desayuno.",
 "calao-rojo": "Idéntico en forma al anterior, pero con el pico **rojo**. Los dos conviven en la misma zona: mira el pico y ya está.",
 "tejedor-republicano": "Se ve **el nido antes que el pájaro**: pajares colectivos gigantes que engullen un árbol o un poste de la luz y que ocupan generaciones enteras.",
 "aguila-marcial": "La mayor águila de África: capucha oscura y pecho blanco moteado. Suele estar posada, inmóvil, en lo alto de una acacia.",
 "buitre-dorsiblanco": "El buitre común de la sabana. El dorso pálido que le da nombre solo se le ve bien en vuelo.",
 "flamenco-enano": "Más pequeño y más intensamente rosa que el común, con el pico oscuro de lejos. **Depende por completo de que haya agua en el pan.**",
 "grulla-azul": "Gris azulada, con la cabeza abultada y unas largas plumas alares que arrastra como una cola. Elegantísima y, aquí, rareza.",
 "ganga-namaqua": "Cola muy puntiaguda; llega a las charcas en bandos y a horas fijas. El macho **empapa las plumas del vientre** para llevarles agua a los pollos.",
 "sison-negro": "El macho es negro con grandes parches blancos en el ala; se delata con un chillido metálico al levantar el vuelo.",
 "azor-lagartijero": "Gris claro, con patas y cera del pico **rojas**. Casi siempre posado en un poste, oteando el suelo.",
 "alcaudon-carmesi": "Negro por arriba y **rojo intenso** por abajo: imposible de confundir. Se mueve por dentro del matorral espeso.",
 "buho-lacteo": "El búho más grande de África, con **párpados rosados** que se le ven al parpadear. En los árboles grandes de los campamentos.",
 "abejaruco-carmin": "Carmesí con la cabeza azul turquesa. Es **migrador de verano austral**: llega al norte del país justo por estas fechas.",
 "ciguena-abdim": "Cigüeña pequeña y oscura, de patas grises con las «rodillas» rojas. Llega con las primeras lluvias y por eso la llaman la cigüeña de la lluvia.",
 "estornino-cabo": "Azul verdoso metálico con el ojo naranja. En los campamentos, siempre atento a las migas de la mesa.",
 "pigargo-vocinglero": "Cabeza blanca y pecho castaño; su reclamo es, literalmente, el sonido de África. Necesita agua abierta, así que aquí depende del pan y de las charcas grandes.",
}
